\clearpage

# SOMMAIRE DE L’ÉTUDE DE CAS DE LA PLIE ROYALE

Nous avons entrepris une étude de cas du stock de plie royale (*Glyptocephalus zachirus*) dans la zone de gestion du poisson de fond (zone 3CD) de la côte ouest de l’île de Vancouver (COIV) afin de démontrer l’application du Cadre des procédures de gestion.
Nous avons choisi ce stock parce qu’il n’a pas de données récentes sur la détermination de l’âge, qu’il n’a pas d’avis d’évaluation à jour et qu’il a un cycle biologique contrastant avec celui du sébaste aux yeux jaunes du détroit de Georgie (*Sebastes ruberrimus*), un stock de poisson auquel ce Cadre a été appliqué simultanément [@haggarty2020yelloweye].
Nous résumons brièvement ici l’étude de cas de la plie royale. Tous les détails sont disponibles dans les annexes \@ref(app:mse-rex) et \@ref(app:desc-om-rex).
L’étude de cas est présentée pour illustrer le cadre et ses sorties, mais *ne vise pas à fournir des avis sur les prises pour le moment*.

La plie royale est un poisson plat pêché principalement au chalut de fond en Colombie Britannique.
Elle peut vivre jusqu’à 29 ans, mesurer jusqu’à 58 cm et peser 1,44 kg.
Des otolithes ont été recueillis régulièrement durant les relevés menés en Colombie Britannique, mais on n’en a pas déterminé l’âge.
La plie royale est capturée régulièrement dans les relevés synoptiques au chalut de fond du MPO et les indices de la biomasse relative calculés à partir de ces relevés ont un niveau relativement faible d’erreur d’observation (CV [coefficient de variation] = 0,07—0,12) comparativement à de nombreux autres stocks de poisson de fond capturés dans le même relevé.
Il n’existe pas d’évaluation des stocks ni de TAC pour la plie royale de la côte ouest de l’île de Vancouver.

**Contexte de la décision** :
La décision à prendre consistait à déterminer la procédure de gestion à utiliser pour définir les limites de prises pour la période allant jusqu’au prochain avis disponible sur les prises.

**Objectifs et paramètres de rendement** :
Nous avons défini des objectifs et des paramètres de rendement selon les suggestions provisoires présentées dans la section \@ref(sec:approach2), qui sont guidées par le Cadre de l’approche de précaution.
Étant donné que la durée de 1,5 à 2 générations de plie royale serait de moins de 50 ans, nous avons choisi d’exécuter nos projections sur 50 ans (section \@ref(sec:approach2)).

Nous avons défini les paramètres de rendement comme suit :

1. LT PRL : Probabilité que *B* > 0,4*B*~RMD~ (années 35--50)
2. LT RSS : Probabilité que *B* > 0,8*B*~RMD~ (années 35--50)
3. FRMD : P(*F* < *F*~RMD~) (années 1--50)
4. STC : Probabilité que les prises > prises de référence (années 1--10)
5. LTC : Probabilité que les prises > prises de référence (années 35--50)
6. AADC : Probabilité que l’AADC (différence interannuelle absolue moyenne des captures) < AADC historique (années 1--50)

où les prises de référence étaient définies comme les prises moyennes des cinq dernières années.

### Spécification des modèles opérationnels
Nous avons établi six modèles opérationnels de l’ensemble de référence englobant l’incertitude relative à l’épuisement du stock avant 1996, la mortalité naturelle (*M*), le taux de variation stock-recrue (*h*), la sélectivité selon la longueur dans la pêche et le relevé, ainsi que l’inclusion ou l’exclusion des données sur l’effort de CPUE dans la pêche commercial (annexe \@ref(app:mse-rex) section \@ref(sec:results-reference-set)).
Nous avons également établi deux modèles opérationnels de l’ensemble de robustesse incluant des sources supplémentaires d’incertitude liées à la structure, moins plausibles mais possibles : 1) un scénario de modèle opérationnel qui suppose que le stock était légèrement exploité avant 1996 et exclut les données sur les CPUE; et 2) un scénario de modèle opérationnel qui évalue la robustesse aux augmentations futures de la mortalité naturelle (pouvant être dues aux changements climatiques ou à des changements dans l’abondance des prédateurs) (annexe \@ref(app:mse-rex), section \@ref(sec:results-robustness-set).

Nous avons documenté le paramétrage initial des modèles opérationnels (annexe \@ref(app:desc-om-rex)) et le conditionnement des modèles opérationnels à l’aide de l’analyse stochastique de la réduction des stocks (ARS; annexe \@ref(app:sra)).
Le conditionnement a permis d’estimer l’épuisement de la biomasse durant la dernière année historique, l’ampleur du recrutement non exploité, la mortalité par pêche selon l’âge par année, et les écarts historiques du recrutement.
Nous n’avons retenu que les combinaisons de paramètres qui présentaient des ajustements plausibles aux données observées dans l’analyse de la réduction des stocks (annexe \@ref(app:mse-rex), section \@ref(sec:results-om-conditioning)).

**Spécification des procédures de gestion possibles** :
Nous avons travaillé avec tout l’ensemble des procédures de gestion possibles provisoires décrites à l’annexe \@ref(app:MPs).
Nous avons modifié les procédures de gestion pour n’observer que les années paires de l’indice de relevé afin de refléter la nature biennale du relevé synoptique du chalut de fond sur la côte ouest de l’île de Vancouver.

**Application de la simulation en boucle fermée** :
Nous avons appliqué des critères de satisfaction fondés sur le point de référence limite à long terme (LT PRL) et les paramètres de rendement des prises à court terme (STC) (LT PRL minimum > 0,9, STC minimum > 0,8). Nous avons écarté certaines procédures de gestion qui avaient un rendement presque identique pour avoir un groupe gérable de sept procédures de gestion pour poursuivre notre examen.
Ces procédures de gestion comprenaient des procédures de gestion indice-cible, des modèles de production excédentaires jumelés à une règle de contrôle des prises, et deux procédures de gestion à prises constantes.

**Présentation des résultats** :
Nous avons présenté un certain nombre de visualisations illustrant les scénarios de l’ensemble de référence de modèles opérationnels pour aider à évaluer les compromis entre les sept procédures de gestion satisfaisantes pour la prise de décision finale.
Nous avons établi la moyenne des résultats pour les scénarios de l’ensemble de référence de modèles opérationnels, afin d’intégrer les diverses incertitudes représentées par ces modèles opérationnels.
Nous avons présenté les résultats de probabilité en termes de moyenne (figures \@ref(fig:rex-tigure-avg)) et de rendement minimal (figures \@ref(fig:rex-tigure-min)), où ce dernier représente le pire des scénarios parmi les scénarios de l’ensemble de référence de modèles opérationnels.
Nous suggérons que les figures \@ref(fig:rex-tigure-avg) et \@ref(fig:rex-tigure-min) constituent la principale source d’information utilisée par les décideurs pour sélectionner la procédure de gestion finale.
Pour faciliter cette décision, nous avons inclus un certain nombre d’autres visualisations pour aider les décideurs à comprendre la dynamique sous-jacente et les compromis des divers modèles opérationnels parmi toutes les procédures de gestion satisfaisantes.

Enfin, nous avons évalué le rendement des procédures de gestion satisfaisantes selon les scénarios de robustesse de modèles opérationnels.
Nous présentons séparément les résultats des deux scénarios de robustesse de modèles opérationnels pour permettre aux décideurs de voir le rendement des procédures de gestion dans ces scénarios moins plausibles de modèles opérationnels.
Un mauvais rendement d’une procédure de gestion dans l’un de ces scénarios de modèles opérationnels peut pousser un décideur à choisir une autre procédure de gestion qui donne de bons résultats dans les scénarios des ensembles de référence et de robustesse de modèles opérationnels.
Quatre procédures de gestion Itarget (annexe \@ref(app:MPs), section \@ref(sec:mp-itarget)) étaient relativement robustes par rapport au scénario de modèle opérationnel où le stock était peu exploité avant 1996 et la mortalité naturelle augmentait dans le futur.
À l’inverse, les procédures de gestion à prises constantes et de production excédentaire affichaient des probabilités beaucoup plus faibles d’atteindre l’objectif du point de référence limite à long terme dans le scénario de robustesse de modèle opérationnel avec un faible taux d’exploitation.

Un ensemble complet de résultats et l’interprétation des résultats sont fournis à l’annexe \@ref(app:mse-rex).
