# DISCUSSION {#sec:discussion}

Dans ce document, nous avons présenté un cadre pour la mise en œuvre d’une approche fondée sur des procédures de gestion pour produire des avis scientifiques sur le poisson de fond en Colombie-Britannique.
Nous y décrivons une approche pour élaborer des modèles opérationnels appropriés, mettre à l’essai des séries de procédures de gestion, et déterminer celles qui répondent le mieux aux objectifs de la gestion des pêches et des intervenants.
Notre objectif final est que le Cadre des procédures de gestion améliore la capacité du MPO à répondre aux exigences du Cadre pour la pêche durable du Canada et des dispositions sur les stocks de poissons de la *Loi sur les pêches* pour les espèces à données limitées.
Bien que le Cadre des procédures de gestion ne mette pas l’accent sur la connaissance explicite des points de référence des stocks de poissons, il privilégie le choix d’approches de gestion qui offrent une forte probabilité de maintenir les stocks de poissons au-dessus des points de référence implicitement connus dans différents états de la nature possibles.
Dans la discussion qui suit, nous mettons en lumière les problèmes liés aux points de référence, à l’ajustement des procédures de gestion, à la fréquence et aux déclencheurs des évaluations, à l’inclusion des effets environnementaux, à l’évaluation de la valeur de l’information, et à l’utilisation de ce Cadre dans les plans de rétablissement des stocks.

## CONNAISSANCE IMPLICITE ET EXPLICITE DES POINTS DE RÉFÉRENCE LIMITES {#sec:discussion-ref-points}

Ce Cadre des procédures de gestion et tous les processus d’évaluation des stratégies de gestion diffèrent des évaluations classiques des stocks pour ce qui est de la façon dont les avis scientifiques sont fournis.
Dans la plupart des évaluations des stocks de poisson de fond de la Colombie-Britannique [p. ex. @yamanaka2011; @starr2017; @forrest2019], les avis sur les prises sont présentés sous forme de tableaux de décision, où les probabilités de dépassement des points de référence (p. ex. la probabilité que les stocks tombent en deçà du PRL) sont présentées pour un éventail de futurs TAC possibles.
L’incertitude peut être intégrée au processus principalement de deux façons : 1) dans un seul modèle, en traitant les paramètres du modèle (p. ex. $M$, $R_0$, $h$, termes d’erreur de processus et d’observation) comme des variables aléatoires; et/ou 2) en élaborant d’autres modèles pour tester la sensibilité aux hypothèses du modèle.
Dans ce dernier cas, on peut moyenner les résultats de certains de ces modèles de sensibilité pour produire un tableau de décision fondé sur la moyenne des modèles [p. ex. @forrest2019], en intégrant les incertitudes entre plusieurs modèles.
Cette approche dépend de la déclaration explicite des points de référence et de l’estimation de l’état des stocks.
À la suite de la production d’un tableau de décision, il incombe aux décideurs de choisir un TAC futur en fonction des probabilités présentées dans le tableau de décision et en tenant compte d’autres facteurs comme les besoins économiques de la pêche combinés à leur tolérance au risque.
Dans ce processus, la prise en compte du risque (c.-à-d. la probabilité de dépasser les points de référence et les impacts qui en découlent) se fait à l’étape finale du processus décisionnel et n'est pas toujours transparente ou liée à des objectifs convenus.

Les cadres de procédures de gestion diffèrent des évaluations conventionnelles de deux manières principales : 1) les points de référence et l’état des stocks ne sont pas explicitement indiqués (ou du moins ne sont pas mis en relief); et 2) les objectifs relatifs à la probabilité de dépasser les points de référence doivent être convenus au début du processus, c’est-à-dire à l’étape 2 des pratiques exemplaires (section \@ref(sec:best2)).
Les points de référence et l’état des stocks font donc toujours partie intégrante du cadre---ils sont calculés dans les modèles opérationnels et intégrés dans les paramètres de rendement.
Il est essentiel de s’entendre sur le risque acceptable (p. ex. les probabilités acceptables de dépassement des points de référence) au début du processus afin de pouvoir établir les paramètres de rendement et les critères de satisfaction.
Le point de décision final dans ce processus est la procédure de gestion qui produit un TAC atteignant les objectifs, tout en réalisant idéalement aussi des compromis acceptables entre d’autres objectifs comme les prises ou la variabilité des prises.
L’un des avantages des cadres de procédures de gestion est que tous les objectifs doivent être énoncés de façon transparente et faire partie intégrante de l’avis final sur les prises.

Nous précisons que, pour de nombreux stocks, en particulier les stocks à données limitées, il n’est pas possible d’estimer de façon fiable leurs points de référence biologiques ou leur état.
Des cadres des procédures de gestion comme celui-ci peuvent être particulièrement importants pour ces stocks.
Le Cadre pour la pêche durable et les dispositions relatives aux stocks de poissons de la *Loi sur les pêches* exigent que les stocks de poissons soient maintenus à des niveaux durables, et en particulier au-dessus du PRL (section \@ref(sec:intro-motivation)).
Ce cadre préserve implicitement l’intention de ces politiques, bien que les points de référence et l’état du stock ne soient pas explicitement fournis.
Le Cadre des procédures de gestion améliore donc la capacité de produire des avis sur les prises conformes au Cadre pour la pêche durable et aux dispositions sur les stocks de poissons pour les stocks à données limitées.
Nous recommandons que des produits comme l’étude sur la durabilité réalisée par le MPO soient souples pour tenir compte des rapports d’étape des processus fondés sur des procédures de gestion, qui peuvent utiliser d’autres formulations comme : « Selon la procédure de gestion actuelle, la probabilité que le stock soit inférieur au PRL moyenné sur une période de [Z]-années est inférieure à [X] ([Y] chances sur [N]). »
Sinon, si on calcule un rendement minimal par année [@ices2016criteria] : « [...] la probabilité que le stock soit inférieur au PRL chaque année pendant une période de [Z] années est inférieure à [X] ([Y] chances sur [N]). »

## RÉGLAGE DES PROCÉDURES DE GESTION {#sec:discussion-tuning}

Bon nombre des procédures de gestion de ce Cadre sont caractérisées par un ou plusieurs paramètres qui contrôlent la façon dont le TAC devrait changer en réponse aux variations de l’indice du relevé (annexe \@ref(app:MPs)).
Par exemple, les procédures de gestion Itarget ont quatre paramètres de « réglage », $w$, $x$, $\lambda$ et $\delta$ qui contrôlent le taux et l’échelle des ajustements du TAC en réponse aux variations de l’indice (annexe \@ref(app:MPs), section \@ref(sec:mp-itarget)).
Dans notre étude de cas de la plie royale, nous avons mis à l’essai six versions des procédures de gestion Itarget sur une échelle assez grossière des paramètres de réglage.
Dans ce cas particulier, plusieurs procédures de gestion ont donné de bons résultats en ce qui concerne les critères de satisfaction, de sorte que nous n’avons pas exploré d’autres combinaisons.
Cependant, dans certaines applications du Cadre, il peut être souhaitable de régler avec précision les procédures de gestion de façon itérative pour atteindre les résultats de rendement visés [voir la discussion sur le réglage des procédures de gestion dans @sagarese2018 ].

Il y a un compromis à faire entre la mise à l’essai d’un plus grand ensemble de procédures de gestion génériques en fonction d’un ensemble approximatif de paramètres de réglages et l’intégration de procédures de gestion plus performantes au moyen de l’étape relative à la satisfaction, plutôt que de concentrer les efforts sur quelques procédures de gestion qui sont très « précises » pour atteindre les résultats souhaités. 
Dans les cas où les procédures de gestion génériques donnent de mauvais résultats, la deuxième approche peut être préférable. 
Cette dernière approche peut également être privilégiée dans des processus plus matures avec une forte mobilisation des intervenants, où les procédures de gestion peuvent être réglées de façon itérative pour atteindre un ensemble d’objectifs plus précis [p. ex. @cox2008a]. 
En fin de compte, la décision d’évaluer des procédures de gestion génériques ou plus précises sera prise au cas par cas pour chaque stock. 
Le processus peut commencer avec des procédures de gestion plus génériques et passer peu à peu à des procédures de gestion plus précises à mesure que l’expérience est acquise avec le rendement de certaines procédures de gestion.

## FRÉQUENCE ET DÉCLENCHEURS DES RÉÉVALUATIONS {#sec:discussion-triggers}

En général, l’objectif d’un cadre des procédures de gestion est de déterminer et de choisir une procédure de gestion solide qui peut être laissée en place pendant une période convenue. 
Nous ne recommandons pas d’intervalle précis entre les évaluations dans ce Cadre et suggérons de le faire stock par stock. 
Selon nous, le Cadre des procédures de gestion lui-même peut être utilisé pour mettre à l’essai des intervalles de réévaluation appropriés pour les différents stocks de poissons [p. ex. @huynh2020]. 
Des vérifications provisoires entre les évaluations sont également recommandées pour s’assurer que la procédure de gestion choisie fonctionne comme prévu.

En plus des étapes des pratiques exemplaires décrites dans la section \@ref(sec:best-practices), @carruthers2018 présentent une étape d’évaluation finale, où le rendement de la procédure de gestion choisie est examiné officiellement une fois qu’elle a été mise en œuvre.
Les écarts par rapport au rendement prévu d’une procédure de gestion ont été qualifiés de « circonstances exceptionnelles », lorsque la dynamique observée du système se situe en dehors de l’éventail des scénarios de modèles opérationnels précisés dans le ou les modèles opérationnels, pour lesquels la robustesse des procédures de gestion a été démontrée [@butterworth2008].
Les circonstances exceptionnelles peuvent être causées soit par une mauvaise spécification du ou des modèles opérationnels originaux, soit par des changements imprévus dans la dynamique future du système qui n’ont pas été saisis dans le modèle opérationnel original (p. ex. changements dans la mortalité naturelle, la croissance, le recrutement ou la dynamique de la pêche).
La preuve de circonstances exceptionnelles, survenant dans l’intervalle recommandé entre les évaluations, déclencherait un examen des modèles opérationnels et de la procédure de gestion, ce qui pourrait entraîner un nouveau modèle opérationnel ou un ajustement de la procédure de gestion choisie [@carruthers_hordyk_2018].

Dans les processus établis d’évaluation des stratégies de gestion [p. ex. @cox2008a], une évaluation informelle du rendement des procédures de gestion peut être effectuée à intervalles réguliers à mesure que la procédure de gestion est appliquée et que de nouvelles données sont recueillies (p. ex. relevé et renseignements sur les CPUE dans la pêche commerciale).
@carruthers_hordyk_2018 donnent plusieurs exemples d’évaluations des stratégies de gestion où des protocoles officiels de détection de circonstances exceptionnelles ont été établis.
En général, les protocoles officiels comprenaient la surveillance de l’indice de la biomasse, des prises et parfois d’autres types de données, comme les données sur la composition selon l’âge, et la comparaison des observations aux prévisions du modèle opérationnel.
Les données observées qui se situent à l’extérieur d’un certain intervalle de confiance des données prédites par le modèle opérationnel (p. ex. 90 % ou 95 %) sont des exemples de déclencheurs de réévaluation.
@carruthers_hordyk_2018 recommandent de tester la puissance statistique des protocoles formels pour détecter les circonstances exceptionnelles.
Cela peut être particulièrement important pour les espèces à données limitées, où la puissance statistique peut être faible en raison d’une grande incertitude dans la dynamique du modèle opérationnel.
Par exemple, si l’intervalle de confiance d’un indice prédit est extrêmement important en raison des incertitudes du modèle opérationnel, la probabilité que les indices observés dans l’avenir se situent à l’extérieur de sa fourchette peut être faible.
Il peut donc être nécessaire d’utiliser des statistiques d’essai plus rigoureuses, peut-être fondées sur plusieurs sources de données [p. ex., exemples donnés dans @carruthers_hordyk_2018].

Nous préconisons d’évaluer régulièrement le rendement des procédures de gestion recommandées par ce Cadre, mais nous reconnaissons qu’un protocole formel n’a pas encore été établi.
Nous recommandons donc aussi d’autres analyses pour évaluer les protocoles de détection des circonstances exceptionnelles en priorité.

## INCLUSION DES EFFETS ENVIRONNEMENTAUX {#sec:discussion-environmental}

Les dispositions sur les stocks de poissons de la *Loi sur les pêches* stipulent que les décisions de gestion des pêches doivent tenir « compte de la biologie du poisson et des conditions environnementales qui influent sur le stock » (section \@ref(sec:intro-motivation)).
Les conditions environnementales changeantes peuvent avoir de nombreuses répercussions sur les stocks de poissons, notamment sur les taux de mortalité naturelle, les taux de croissance et l’état, le succès du recrutement et la répartition spatiale, ce qui peut avoir une incidence sur la capturabilité ou la sélectivité des pêches.
Les milieux décisionnels des pêches ne disposent pas de méthodes solides bien établies pour inclure des considérations environnementales dans les avis sur les prises d’une seule espèce [mais voir @haltuch2011; @haltuch2019; @crone2019].
Cela est dû aux grandes incertitudes associées à l’observation d’environnements marins complexes et à la compréhension des mécanismes reliant la dynamique des populations de poissons aux changements environnementaux [@myers1995].
À moins que les mécanismes soient bien compris [p. ex. @swain2015], l’intégration des variables environnementales dans les évaluations des stocks ne permet pas nécessairement d’améliorer les avis [@punt2014].

Les essais par simulation en boucle fermée sont un moyen important d’évaluer le rendement des procédures de gestion en présence d’incertitude et d’un environnement changeant [p. ex. @haltuch2009; @haltuch2011; @punt2011b].
Dans cette approche, les hypothèses concernant l’impact des variables environnementales sur la dynamique des populations sont intégrées dans les modèles opérationnels, et le rendement des procédures de gestion de rechange (qui peuvent ou non inclure des variables environnementales) est évalué de la façon présentée dans ce Cadre.
Il est possible d’élaborer plusieurs modèles opérationnels qui représentent différentes hypothèses pour les effets environnementaux.
Les modèles opérationnels pourraient inclure explicitement des variables environnementales (p. ex. établir un lien entre la température de l’océan et les écarts du recrutement ou entre l’abondance des prédateurs et *M*) ou pourraient ne pas comporter de mécanisme (p. ex. laisser les paramètres de croissance ou $M$ varier dans le temps sans facteur particulier).
Ces dernières approches sans mécanisme sont déjà faciles à intégrer dans les modèles opérationnels de DLMtool, au moyen de paramètres de croissance ou de mortalité (voir la section \@ref(sec:dlmtool-time-varying)).
L’étude de cas de la plie royale comprenait un scénario de modèle opérationnel dans l’ensemble de robustesse où $M$ augmentait linéairement dans le temps. Dans ce cas, aucun mécanisme précis n’était fourni pour faire varier $M$.

Les changements environnementaux peuvent aussi accroître la fréquence des événements imprévus comme les épisodes de recrutement très fort ou très faible.
Ces événements sont parfois appelés « cygnes noirs » [p. ex. @taleb2007; @anderson2017; @anderson2019] ou « recrutement spasmodique » [@caddy1983], et on peut les intégrer aux modèles opérationnels en ajoutant d’autres distributions pour les anomalies de recrutement afin de tenir compte de ces événements occasionnels.
Une application prochaine du Cadre des procédures de gestion pour le stock de sébaste aux yeux jaunes des eaux intérieures comprendra un scénario de modèle opérationnel qui incorporera des épisodes occasionnels et soudains de recrutement important [@haggarty2020yelloweye].
Nous recommandons d’utiliser les outils élaborés aux fins de ce Cadre pour explorer plus à fond les méthodes d’essai par simulation pour déterminer des procédures de gestion qui demeurent valides dans des conditions environnementales changeantes.

## ÉVALUATION DE LA VALEUR DE L’INFORMATION {#sec:discussion-voi}

Le Cadre des procédures de gestion fournit les outils nécessaires pour évaluer la « valeur de l’information » par rapport au rendement des procédures de gestion.
Les analyses de la valeur de l’information permettent d’évaluer si l’ajout de ressources investies dans la collecte de données permet d’améliorer le rendement.
Ces analyses peuvent également permettre d’évaluer, à l’inverse, si un rendement semblable pourrait être atteint si moins de données étaient disponibles.
Il s’agit essentiellement d’analyses de sensibilité à l’ajout ou l’élimination de sources de données ou aux changements touchant la quantité ou la qualité des données.

Les types de données classiques qui pourraient être incluses dans les analyses de la valeur de l’information dans les applications du Cadre des procédures de gestion pour le poisson de fond de la Colombie-Britannique sont les données sur les indices de relevé et sur la composition selon l’âge.
En ce qui concerne les données sur les indices de relevé, ce cadre pourrait servir à vérifier la sensibilité du rendement de la procédure de gestion aux changements de précision des indices de la population.
Par exemple, les applications du Cadre pourraient quantifier le changement prévu de la probabilité de maintenir un stock au-dessus de son PRL à long terme, compte tenu des réductions ou des expansions des programmes de relevés à stratification aléatoire.

Le Cadre des procédures de gestion pourrait également être utilisé pour évaluer si la détermination de l’âge à partir des otolithes pourrait améliorer le rendement des procédures de gestion pour un stock donné.
Pour ce faire, on utiliserait le modèle opérationnel pour simuler les données sur la composition selon l’âge, peut-être avec des tailles effectives de l’échantillon différentes, et on vérifierait si les procédures de gestion qui dépendent des données sur la composition selon l’âge (p. ex. un modèle complet structuré selon l’âge) ont un rendement supérieur aux procédures de gestion plus simples et à données limitées, comme celles qui sont mises à l’essai dans le présent document.
Le progiciel d’accompagnement de DLMtool, MSEtool, contient un grand nombre de procédures de gestion riches en données (modèles structurés selon l’âge) qui pourraient être utilisées à cette fin [@huynh_msetool_2019].
Ce type d’analyse pourrait servir à déterminer si des procédures de gestion riches en données répondraient mieux aux objectifs de gestion d’un stock de poissons donné et, le cas échéant, de la quantité de données sur la détermination de l’âge nécessaire pour une évaluation complète [p. ex. @sagarese2018].
Les effets des biais et de l’imprécision de la détermination de l’âge sur le rendement de l’évaluation pourraient également être évalués.
Nous soulignons qu’il peut être difficile de simuler des données sur la composition selon l’âge et la longueur avec un « bruit » suffisamment réaliste.
L’évaluation du rendement des procédures de gestion à l’aide de données sur la composition qui représentent la composition sous-jacente réelle plus étroitement que les données réelles peut surestimer le rendement des procédures de gestion qui dépendent des données sur la composition.

À notre avis, l’élargissement du Cadre pour inclure des considérations sur la valeur de l’information pourrait également nécessiter l’élaboration de nouveaux objectifs et paramètres de rendement liés aux coûts associés à l’expansion des programmes de recherche, à la collecte de plus de données ou à des avantages comme des améliorations marginales de l’exactitude des avis et des améliorations de l’accessibilité des prises.

## PLANS DE RÉTABLISSEMENT {#sec:discussion-rebuilding}

La \link{https://waves-vagues.dfo-mpo.gc.ca/Library/40584781.pdf}{Politique sur l’approche de précaution} et les dispositions sur les stocks de poissons de la *Loi sur les pêches* (section \@ref(sec:intro-motivation)) exigent que des mesures de gestion soient mises en place si l’on évalue que les stocks de poissons se trouvent dans la zone critique (c.-à-d. sous le PRL).
Les plans de rétablissement requièrent que les mesures de gestion fassent sortir les stocks de la zone critique dans un délai précis (p. ex. une ou deux générations), avec une probabilité déterminée.
Le Cadre des procédures de gestion peut être facilement modifié pour tester le rendement des autres procédures de gestion en ce qui concerne l’atteinte des objectifs de rétablissement des stocks nécessitant des plans de rétablissement.
Les seules véritables modifications nécessaires sont les objectifs et les paramètres de rendement, qui sont déjà personnalisables dans ce Cadre.

Pour les espèces à données limitées, l’un des défis est de déterminer si un stock se trouve dans la zone critique, ce qui est nécessaire pour déclencher un plan de rétablissement.
À la lumière des nouvelles exigences législatives concernant le rétablissement dans les dispositions sur les stocks de poissons, la Direction des sciences du MPO élabore actuellement des directives plus détaillées sur les facteurs à prendre en considération pour concevoir des programmes de rétablissement [@kronlund2020].
En s’appuyant sur les précédents établis par Santé Canada, [@weight2018], @kronlund2020 suggère une approche fondée sur le « poids de la preuve » pour déterminer si le rétablissement est nécessaire.
Une approche fondée sur le poids de la preuve peut comprendre la prise en compte des contributions combinées de différentes études (ensemble de la preuve) et des valeurs attribuées par jugement d’expert à chaque source de données, lorsqu’une source de données peut comprendre une ou plusieurs études.
Nous sommes d’avis que, dans les cas où les modèles opérationnels conditionnés établissent une forte probabilité qu’un stock de poissons se trouve dans la zone critique pour une gamme d’hypothèses plausibles de modèles opérationnels, cela pourrait contribuer aux sources de données utilisées pour déclencher un plan de rétablissement.

Ce cadre est actuellement appliqué pour évaluer d’autres procédures de gestion à données limitées pour le plan de rétablissement du stock de sébaste aux yeux jaunes des eaux intérieures en Colombie-Britannique [@haggarty2020yelloweye].

## STOCKS À DONNÉES MODÉRÉES ET À DONNÉES ABONDANTES {#sec:discussion-data-rich}

Ce Cadre décrit les étapes nécessaires pour évaluer le rendement des procédures de gestion à données limitées, en mettant l’accent sur les espèces de poisson de fond de la Colombie-Britannique.
La richesse en données se produit le long d’un gradient et il peut être souhaitable d’appliquer le Cadre pour évaluer le rendement des procédures de gestion à données modérées ou abondantes.
Les principes de ce Cadre sont les mêmes dans le continuum de la richesse en données.
Le progiciel MSEtool dans R [@huynh_msetool_2019] contient des procédures de gestion à données modérées (p. ex. modèles de type différence-délai) et abondantes (p. ex. modèles statistiques des prises selon l’âge) qui pourraient facilement être intégrées à ce Cadre avec quelques modifications.
Cependant, nous précisons encore une fois que le Cadre est indépendant du logiciel.
D’autres logiciels ont été utilisés de la même façon pour des espèces à données riches en Colombie-Britannique [p. ex. la morue charbonnière : @cox2008a; hareng du Pacifique : @cox2019].


## LIMITES DU CADRE {#sec:discussion-limitations}

Comme pour tous les processus d’évaluation des stratégies de gestion, les résultats de ce Cadre dépendront de la mesure dans laquelle les incertitudes du système réel sont exprimées dans les modèles opérationnels.
C’est pourquoi nous avons recommandé d’élaborer plusieurs modèles opérationnels pour saisir les hypothèses clés les plus plausibles au sujet du système dans l’ensemble de référence, ainsi qu’un plus large éventail d’incertitudes dans l’ensemble de robustesse.
Cependant, il est inévitable que certaines incertitudes ne soient pas prises en compte, soit parce qu’elles sont inconnues, soit parce que leur inclusion créerait une complexité inapplicable dans l’environnement de modélisation et de prise de décisions, comme les espèces pour lesquelles les considérations spatiales sont importantes (p. ex. les espèces hautement migratrices) ou les espèces dont la productivité est fortement influencée par l'environnement.
Certaines considérations seront inévitablement prises en compte en dehors de la portée du processus en raison des limites des données disponibles, du temps ou de l’expertise.
Il est donc important d’évaluer le rendement de certaines procédures de gestion une fois qu’elles sont mises en œuvre, par des moyens informels ou formels (section \@ref(sec:discussion-triggers)).

Nos modèles opérationnels ont été conditionnés en fonction des données observées, à l’aide du modèle d’analyse de la réduction des stocks dans MSEtool.
Les sorties du modèle dépendent de la qualité des données disponibles, ainsi que des distributions présumées de ses paramètres d’entrée.
En particulier, les hypothèses sur la sélectivité constitueront une source d’incertitude clé pour les espèces pour lesquelles il y a peu ou pas de données sur la composition selon l’âge.
Il faudrait donc traiter la sélectivité comme un axe d’incertitude dans la plupart des applications.
De plus, comme un modèle d’analyse de la réduction des stocks suppose qu’il n’y a presque pas d’erreur d’observation dans les données historiques sur les prises, l’incertitude peut être sous-estimée dans ses sorties.
Pour le poisson de fond de la Colombie-Britannique pêché au chalut, les estimations des prises sont considérées comme fiables depuis l’introduction, en 1996, du niveau de présence à 100 % des observateurs en mer.
Pour les espèces capturées à la ligne, les données sur les prises sont considérées comme fiables depuis l’introduction de la surveillance électronique à 100 % en 2006. Pour certaines espèces, surtout celles qui ont une faible valeur monétaire, les données sur les prises avant ces années peuvent être plus incertaines et il peut être nécessaire d’inclure d’autres scénarios pour tenir compte de l’incertitude dans les prises [p. ex. @haggarty2020yelloweye].

<!-- Nous avons présenté une sélection de procédures de gestion empiriques et fondées sur des modèles pour les espèces à données limitées, mais les applications futures du cadre pourraient nécessiter d’évaluer d’autres procédures de gestion, publiées dans la documentation ou élaborées dans le cadre du processus même d’évaluation des stratégies de gestion [p. ex. @cox2008a]. -->

Enfin, le succès de ce Cadre et de tout processus d’évaluation des stratégies de gestion dépendra de la participation adéquate des gestionnaires des pêches, des Premières Nations et des intervenants.
Pour certaines espèces, différents groupes d’utilisateurs peuvent avoir des objectifs variés, ce qui crée d’importants compromis et un environnement décisionnel complexe.
Dans ces cas, il sera particulièrement important de bien gérer le processus et de porter attention aux étapes 1 et 2 (section \@ref(sec:best-practices)).

# REMERCIEMENTS

Nous remercions les membres de notre groupe consultatif technique, Rob Kronlund, Adam Keizer, Chris Grandin, Ashleen Benson, Dana Haggarty, Rowan Haigh, Roger Kanno, Paul Starr, Rob Tadey et Greg Workman, pour leurs discussions et commentaires utiles sur les versions antérieures de ce document.

Nous remercions Chris Grandin, qui a mis au point un certain nombre de fonctions de visualisation et de génération de rapports dans le progiciel ggmse R, qui ont grandement amélioré ce document et qui seront d’une valeur inestimable dans les applications du Cadre.

Nous remercions Tom Carruthers et Adrian Hordyk de leur travail de développement de DLMtool et MSEtool. Ce projet aurait été beaucoup plus vaste sans ces outils. Les conseils utiles de Tom et d’Adrian et leur disponibilité pour ajouter de nombreuses nouvelles fonctions sur demande ont grandement amélioré ce cadre.

Nous remercions John Holmes, qui a soutenu notre travail sur ce Cadre dans la Division de l’évaluation des stocks et de la recherche à la Station biologique du Pacifique.

Nous remercions Jaclyn Cleary et Ann-Marie Huang pour leurs conseils utiles sur d’autres processus d’évaluation des stratégies de gestion en Colombie-Britannique.

Nous remercions le Programme de contribution aux sciences marines et d’eaux douces du MPO, qui a appuyé l’élaboration de DLMtool et de MSEtool.

Enfin, nous remercions Carrie Holt et Meaghan Bryan pour leurs commentaires judicieux qui ont grandement amélioré ce document.

