\clearpage

`r if(knitr:::is_latex_output()) '\\Appendices'`
`r if(!knitr:::is_latex_output()) '# (APPENDIX) Appendix {-}'`

# MODÈLE OPÉRATIONNEL DE DLMTOOL {#app:dlmtool-om}

Le modèle opérationnel (MO) de la dynamique des populations, tel qu’il est mis en œuvre dans DLMtool, est un modèle structuré selon l’âge décrit ci-après.
Le modèle opérationnel est flexible et offre des options permettant à un certain nombre de paramètres (p. ex. mortalité naturelle, croissance, sélectivité) de varier dans le temps (voir la section \@ref(sec:dlmtool-time-varying)).
Il est aussi possible de décrire plusieurs sous-zones, ainsi que de représenter l’incertitude des résultats en ajoutant des paramètres d’incertitude de la mise en œuvre et de biais.
La documentation complète du modèle opérationnel de DLMtool, y compris la gamme des paramétrages possibles, est décrite dans les annexes de @carruthers2018 et adaptée ici pour le Cadre des procédures de gestion.
Ici, nous adaptons la documentation indiquée dans @carruthers2018, en suivant leurs conventions de notation autant que possible dans un souci de cohérence.
Nous présentons la version la plus simple du modèle opérationnel, sans paramètres variables dans le temps ou sous-zones multiples.
Cette structure simple de modèle opérationnel devrait convenir comme modèle opérationnel de base pour la plupart des stocks destinés à être évalués dans le Cadre.
Des hypothèses structurelles plus complexes, y compris des paramètres variables dans le temps, pourraient être élaborées comme scénarios de modèles opérationnels lorsqu’elles sont justifiées pour des stocks en particulier.

En suivant l’exemple de @carruthers2018, nous désignons les paramètres définis par l’utilisateur et échantillonnés de façon stochastique sur les répétitions par un tilde (p. ex. $\widetilde{M}$). Par exemple, $\widetilde{M_i} \sim f \left( \theta \right)$ représente le $i^\textrm{th}$ tirage dans la simulation du paramètre $M$ échantillonné à partir de la fonction de distribution $f$ et des paramètres $\theta$.
Dans la plupart des cas, les paramètres stochastiques pourraient être échantillonnés à partir d’une distribution uniforme ou précisés directement après l’échantillonnage à partir d’une distribution ou d’un modèle quelconque.

Le cadre de simulation comporte deux périodes distinctes :
1) la période historique, qui comprend les années allant de la première année de la série chronologique des prises $t_1$ à la dernière année de la série chronologique des prises $t_c$ (où « c » représente l’année « en cours »);
2) la période de projection, qui va de la première année suivant $t_c$ à la dernière année de la projection $t_N$. 
La période historique est conditionnée en fonction des observations historiques à l’aide d’une analyse de la réduction des stocks structurée selon l’âge [ARS; @kimura1982; @walters2006], décrite à l’annexe \@ref(app:sra).
La simulation en boucle fermée, avec application des procédures de gestion et calcul des paramètres de rendement, commence la première année de la période de projection (année $t_{c}+1$).

L’élaboration d’un modèle opérationnel dans le Cadre des procédures de gestion comporte trois étapes :

1. Établir les valeurs et les plages des paramètres du MO---Les équations du MO sont fournies dans cette annexe; les principaux paramètres sont définis dans le tableau \@ref(tab:tab-om-pars); les réglages par défaut des paramètres figurent à l’annexe \@ref(app:default-slots). Les valeurs des paramètres peuvent être tirées de données biologiques et halieutiques, d’évaluations des stocks locaux, de la documentation scientifique, de méta-analyses d’espèces semblables, d’évaluations des stocks dans d’autres régions, de jugements d’experts ou d’autres sources, le cas échéant. Des exemples de réglages de paramètres définis par l’utilisateur et tirés d’une gamme de sources sont fournis à l’annexe \@ref(app:desc-om-rex), et dans @haggarty2020yelloweye.

2. Envoyer les paramètres du modèle opérationnel dans le modèle d’analyse de la réduction des stocks, qui conditionne le modèle opérationnel en ajustant une analyse de la réduction des stocks structurée selon l’âge aux prises observées et aux indices de l’abondance (avec des options pour l’ajuster aux données sur la composition selon l’âge ou la longueur si elles sont disponibles).
On obtient des estimations conditionnées des paramètres du modèle et des estimations de la biomasse historique et de la mortalité historique par pêche (les années $t_1$ à $t_c$), qui sont conformes aux observations historiques.
Les équations pour le modèle d’analyse de la réduction des stocks sont fournies à l’annexe \@ref(app:sra).

3. Renvoyer les valeurs des paramètres conditionnés au modèle opérationnel (maintenant le modèle opérationnel « conditionné ») pour les utiliser dans les projections de simulation en boucle fermée, à partir de l’année $t_{c}+1$.

L’analyse de la réduction des stocks met à jour un ou plusieurs des paramètres suivants du modèle opérationnel, en fonction de la disponibilité des données (voir plus de détails à l’annexe \@ref(app:sra)) :

- $B_{t_c}/B_0$ (ou « D »; épuisement au cours de la dernière année historique $t_c$)
- $R_0$ (recrutement non exploité)
- $\theta_\textrm{AC}$ (ou « AC »; autocorrélation de premier ordre des écarts de recrutement)
- $\varepsilon_{\textrm{R},y}$ pour les années $t_1$ à $t_c$ (écarts annuels de recrutement pour la période historique)
- $F_{a,y}$ (mortalité par pêche selon l’âge, par année, pour la période historique)
- Paramètres de sélectivité (fondés sur l’âge ou la longueur).

Ces paramètres sont définis en contexte dans les sections qui suivent. Les paramètres non mis à jour sont utilisés comme spécifié dans le modèle opérationnel.

Il convient de noter que la covariance entre les estimations des paramètres de l’analyse de la réduction des stocks est préservée lorsqu’elles sont renvoyées dans le modèle opérationnel.
En général, la covariance entre d’autres paramètres spécifiés n’est pas prise en compte puisque les paramètres sont précisés par des valeurs ou des distributions uniques.
Toutefois, il est possible d’inclure la covariance entre les paramètres si cette information est disponible. Par exemple, les distributions des paramètres de croissance et de maturité pour l’étude de cas de la plie royale sont tirées de leurs distributions de probabilité a posteriori (annexe \@ref(app:desc-om-rex), section \@ref(app:desc-stock-rex)).

## MODÈLE DE DYNAMIQUE DES POPULATIONS {#sec:dlmtool-pop-dynamics}

<!-- Parameters for the population dynamics are included in the `Stock` object of DLMtool. -->

### Croissance et maturité

Le modèle opérationnel suppose que la croissance suit un modèle de von Bertalanffy :

$$
L_{a} = \widetilde{L}_{\infty}\left( 1 - \exp( - \widetilde{\kappa}(a - \widetilde{t}_{0} \right)),
(\#eq:dlm-om-vonb)
$$

où $L_a$ représente la longueur selon l’âge, $a$, $\widetilde{\kappa}$ le taux de croissance, $\widetilde{L}_{\infty}$ la longueur maximale et $\widetilde{t}_0$ l’âge théorique où la longueur est de zéro.

On suppose que le poids selon l’âge ($w_a$) est lié à la longueur selon l’âge ($L_a$) par la formule :

$$
w_{a} = \widetilde{\alpha}_{W}\ {L_{a}}^{\widetilde{\beta}_{W}},
(\#eq:dlm-om-wta)
$$


où $\alpha_W$ et $\beta_W$ sont des coefficients longueur-poids propres à l’espèce.
La maturité est précisée en fonction de la longueur, à l’aide d’un modèle logistique avec des paramètres décrivant la longueur à 50 % de maturité ($\widetilde{\theta}_{l50}$) et l’augmentation de la longueur de 50 % à 95 % de maturité ($\widetilde{\theta}_{l50-95}$). La maturité ($m_l$) à la longueur ($l$) est alors calculée comme suit :

$$
m_{l} = \frac{1}{1 + e^{{- \ln}19\left( \frac{l - \widetilde{\theta}_{l50}}{{\widetilde{\theta}}_{l50-95}} \right)}},
(\#eq:dlm-om-matl)
$$

où la maturité ($m_a$) selon l’âge est calculée à partir de la longueur selon l’âge :

$$
m_{a} = \frac{1}{1 + e^{{- \ln}19\left( \frac{a - \theta_{a50}}{\theta_{a95} - \theta_{a50}} \right)}},
(\#eq:dlm-om-mata)
$$

et \(\theta_{a50}\) and \(\theta_{a95}\) représentent l’âge à 50% et 95% de maturité donné par la courbe de croissance inverse de von Bertalanffy :

<!-- TODO: check these! -->
$$
\theta_{a50} = \frac{- \ln\left( 1 - \widetilde{\theta}_{l50} / \widetilde{L}_{\infty} \right)}{\widetilde{\kappa}} + \widetilde{t}_{0},
(\#eq:dlm-om-invonb)
$$

$$
\theta_{a95} = \frac{- \ln\left( 1 - \left( \widetilde{\theta}_{l50} / \widetilde{L}_{\infty} + {\widetilde{\theta}}_{l50\_ 95} / \widetilde{L}_{\infty} \right) \right)}{\widetilde{\kappa}} + \widetilde{t}_{0}.
(\#eq:dlm-om-theta95)
$$

### Dynamique des populations

Les paramètres avancés du modèle de dynamique des populations, définis comme des valeurs fixes ou des fourchettes par l’utilisateur, sont les suivants : recrutement non exploité $R_0$, paramètre du taux de variation de la relation stock-recrue ($h$) [@mace1988] et mortalité naturelle ($M$).
Le recrutement et le nombre selon l’âge sont initialisés la première année historique à l’aide du modèle d’analyse de la réduction des stocks (annexe \@ref(app:sra), équations \@ref(eq:sra-om-numinit) à \@ref(eq:sra-om-recinit)). Pendant la période de projection (années $y = t_{c}+1$ à $y = t_N$), le nombre de poissons recrutés dans le premier groupe d’âge au début de chaque année $N_{y,a=1}$ est calculé comme une fonction de la biomasse féconde de l’année précédente $B_{y-1}$.
Le Cadre suppose une relation stock-recrue de Beverton-Holt [@beverton1957] avec écarts de recrutement annuels log-normaux $\varepsilon_{R,y}$, mais les analystes peuvent également choisir une fonction de Ricker [@ricker1954] :

$$
N_{y, a = 1} = R_y =
\begin{cases}
      \dfrac{\alpha^{\textrm{B}} B_{y-1}}{1 + \beta^{\textrm{B}}B_{y-1}} \varepsilon_{R,y} & \textrm{Beverton-Holt}\\
      \alpha^{\textrm{R}} B_{y-1} \exp(-\beta^{\textrm{R}} B_{y-1})\varepsilon_{R,y} & \textrm{Ricker},
\end{cases}
(\#eq:dlm-om-rya)
$$

où $\alpha^{\textrm{B}}$ et $\beta^{\textrm{B}}$ sont les paramètres de la relation stock-recrue de Beverton-Holt, et $\alpha^{\textrm{R}}$ et $\beta^{\textrm{R}}$ sont les paramètres de la relation stock-recrue de Ricker, dérivés du taux de variation des paramètres définis par l’utilisateur ($\widetilde{h}$) and $\widetilde{R}_0$, où
$\alpha^{\textrm{B}} = \frac{4\tilde{h}}{(1-\tilde{h})\phi_0}$,
$\beta^{\textrm{B}} = \frac{5\tilde{h}-1}{(1-\tilde{h})B_0}$
et
$\alpha^{\textrm{R}} = \frac{(5\tilde{h})^{1.25}}{\phi_0}$,
$\beta^{\textrm{R}} = \frac{\log(5\tilde{h})}{B_0}$.
Le paramètre $\phi_0$ est le nombre de reproducteurs par recrue non exploités (voir l’équation \@ref(eq:dlm-om-phi), avec $F^e=0$) et $B_{0}$ est la biomasse féconde non exploitée, calculée comme suit :

$$
B_{0} = \sum_{a = 1}^{A}{m_{a}\ w_{a}\ \widetilde{R}_{0}e^{-\widetilde{M}{(a-1)}}},
(\#eq:dlm-om-bo)
$$

où $A$ est l’âge maximal défini par l’utilisateur et $\widetilde{R}_{0}e^{\widetilde{M}{(a-1)}}$ donne les nombres selon l’âge non exploités. La biomasse féconde $B_y$ d’une année donnée est calculée comme suit :

$$
B_{y} = \sum_{a = 1}^{A}{w_{a}m_{a}N_{y,a}},
(\#eq:dlm-om-sy)
$$

où $N_{y,a}$ correspond aux nombres selon l’âge annuels, donnés dans l’équation \@ref(eq:dlm-om-nya).

Les écarts de recrutement annuels logarithmiques ($\log \varepsilon_{R,y}$) sont générés par le premier échantillonnage selon une distribution normale avec l’écart-type $\widetilde{\sigma}_R$ :

$$
\log \delta_{R,y}\sim \mathrm{Normal}\left(
\frac{-0.5 \widetilde{\sigma}_R^2 (1 - \widetilde{\theta}_\textrm{AC})}{\sqrt{1 - \widetilde{\theta}_\textrm{AC}^2}},
\widetilde{\sigma}_R \right),
(\#eq:dlm-om-recdev)
$$

où le terme moyen comprend une correction de biais moyen pour les variables log-normales autocorrélées et le terme $\widetilde{\theta}_{\textrm{AC}}$ représente l’autocorrélation de premier ordre. Nous utilisons la notation Normal (moyenne, écart-type) plutôt que Normal (moyenne, variance) ici et dans tout le document. L’autocorrélation temporelle $\widetilde{\theta}_\textrm{AC}$ est ajoutée à ces tirages initiaux comme suit :

$$
\log \varepsilon_{R,y} = {\widetilde{\theta}}_{\textrm{AC}}\log \varepsilon_{R,y - 1} + \delta_{R,y}\sqrt{\left( 1 - {{\widetilde{\theta}}_{\textrm{AC}}}^{2} \right)},
(\#eq:dlm-om-auto)
$$

$$
\varepsilon_{R,y} = \exp \left( \log \varepsilon_{R,y} \right).
(\#eq:dlm-om-recdev-exp)
$$

On calcule ensuite le nombre de poissons $N$ chaque année à partir des chiffres de l’année précédente et de la catégorie d’âge, en fonction du taux de mortalité totale instantanée ($Z$) à l’âge ($a$) :

$$
N_{y,a} =
\begin{cases}
      R_y & a = 1\\
      N_{y-1,a-1}\  e^{-Z_{y-1,a-1}} & 1<a<A\\
      N_{y-1,a-1}\  e^{-Z_{y-1,a-1}} + N_{y-1,a}\ e^{-Z_{y-1,a}} & a = A,
\end{cases}
(\#eq:dlm-om-nya)
$$

où $A$ est la classe d’âge maximale et le taux de mortalité annuelle totale $Z_{y,a}$ est donné par la formule :

$$
Z_{y,a} = \widetilde{M} + v_{a}F_{y,a},
(\#eq:dlm-om-zya)
$$

où $F_{y,a}$ est la mortalité selon l’âge par pêche au cours de l’année $y$, définie dans l’équation \@ref(eq:dlm-om-Fay)) et $v_{a}$ est la sélectivité selon l’âge, définie dans l’équation \@ref(eq:dlm-om-va).

Il convient de noter que l’équation \@ref(eq:dlm-om-nya) traite la classe d’âge maximale $A$ comme un groupe plus (c.-à-d. que la classe d’âge $A$ comprend tous les poissons d’âge $A$ et plus).
Ce n’est pas la valeur par défaut dans DLMtool, qui pose habituellement l’hypothèse que $A$ est suffisamment grande pour inclure toutes les classes d’âge (c.-à-d. qu’on utilise $N_{y,a} = N_{y-1,a-1}e^{-Z_{y-1,a-1}}$ pour toutes les classes d’âge, y compris $a = A$).
Cependant, lorsque le modèle est conditionné à l’aide de l’analyse de la réduction des stocks (annexe\@ref(app:sra)), l’analyse de la réduction des stocks traite par défaut $A$ comme un groupe plus (équation \@ref(eq:sra-om-nya)) et, pour assurer la cohérence entre les périodes historiques et de projection, l’analyse de la réduction des stocks force DLMtool à traiter également $A$ comme un groupe plus pour les simulations en boucle fermée dans la période de projection.
Comme nous recommandons de toujours conditionner les modèles opérationnels pour le poisson de fond de la Colombie-Britannique à l’aide de l’analyse de la réduction des stocks, nous incluons le groupe plus dans l’équation \@ref(eq:dlm-om-nya).

## DYNAMIQUE DE LA FLOTTILLE {#sec:dlmtool-fleet-dynamics}

Pendant la période de projection, le taux de mortalité selon l’âge par pêche ($F_{y,a}$) est calculé à partir du TAC prescrit par la procédure de gestion ($\textrm{TAC}_{\mathrm{MP},y}$). Pour répartir les prises entre les âges, il faut d’abord calculer la distribution de la biomasse vulnérable ($B^V_{y,a}$) entre les âges :

$$
B^V_{y,a} = N_{y,a} w_{a} v_{a} \dot{R}_{a}
(\#eq:dlm-om-vulcom)
$$

où $\dot{R_a}$ représente le taux de rétention selon l’âge et la sélectivité selon l’âge $v_{a}$ (ou la vulnérabilité selon l’âge) est calculée selon que les utilisateurs définissent la sélectivité comme étant asymptotique (logistique) ou en forme de dôme, en utilisant la fonction de longueur suivante :

$$
v_{a} =
\begin{cases}
2^{-\frac{(\widetilde{L}_{a} - \widetilde{L}^{\textrm{FS}})^2}{\widetilde{\sigma}^2_{\textrm{asc}}}} & \textrm{if } L_{a} < \widetilde{L}^{\textrm{FS}},\\
1 & \textrm{if logistic and } L_{a} \ge \widetilde{L}^{\textrm{FS}},\\
2^{-\frac{(\widetilde{L}_{a} - \widetilde{L}^{\textrm{FS}})^2}{\widetilde{\sigma}^2_{\textrm{des}}}} & \textrm{if dome-shaped and } L_{a} \ge \widetilde{L}^{\textrm{FS}}
\end{cases}
(\#eq:dlm-om-va)
$$

où $\widetilde{L}^\textrm{FS}$ représente la longueur à la sélectivité totale définie par l’utilisateur. L’écart-type du membre ascendant ($\widetilde{\sigma}_{\textrm{asc}}^{2}$) est donné par la formule :

$$
\sigma_{\textrm{asc}} = \frac{{\widetilde{L}}^{5} - \widetilde{L}^\textrm{FS}}{\sqrt{- \log_{2} 0.05}}
(\#eq:dlm-om-siglasc)
$$

où $\widetilde{L}^5$ est la longueur à 5 % de sélectivité définie par l’utilisateur.

L’écart-type du membre descendant est donné par la formule :

$$
\sigma_{\textrm{des}} = \frac{\widetilde{L}_\infty - \widetilde{L}^\textrm{FS}}{{\sqrt{- \log_{2} {\widetilde{V}_{L_\infty}}}}},
(\#eq:dlm-om-sigldes)
$$

où $\widetilde{V}_{L_\infty}$ est la sélectivité à la longueur maximale définie par l’utilisateur. Le réglage de ce paramètre à 1 force la sélectivité à être logistique (l’équation \@ref(eq:dlm-om-sigldes) n’est pas définie lorsque $\widetilde{V}_{L_\infty} = 1$).

L’outil DLMtool modélise actuellement toutes les prises comme si elles provenaient d’une seule flottille.
Toutefois, si le modèle opérationnel est conditionné à l’aide du modèle d’analyse de la réduction des stocks (annexe \@ref(app:sra)), l’analyse de la réduction des stocks peut intégrer plusieurs flottilles, et la sélectivité est propre à la flottille.
La sélectivité propre à la flottille dans l’analyse de la réduction des stocks est calculée à l’aide de l’équation \@ref(eq:sra-om-vaf) avec des paramètres propres à la flottille définis par l’utilisateur pour $\widetilde{L}^5$, $\widetilde{L}^{FS}$ et $\widetilde{V}_{L_\infty}$, ou elle est estimée si des données sur la composition selon l’âge ou la longueur sont fournies.
Dans ce cas, la sélectivité dans le modèle opérationnel de DLMtool pendant la période de projection est remplacée dans l’équation \@ref(eq:dlm-om-zya) par l’estimation conditionnée par l’analyse de la réduction des stocks de la mortalité selon l’âge par pêche la dernière année ($t_c$) de la période historique($\Sigma_f v_{a,f} F_{t_c,f}$), normalisée en la divisant par la valeur apicale de $F$ ($F$ maximale entre les âges) cette année-là.
On obtient des fractions de $F$ selon l’âge dérivées de la sélectivité relative selon l’âge entre les flottilles (c.-à-d. la sélectivité selon l’âge pondérée par les prises).
Les projections de simulation en boucle fermée supposent donc que les sélectivités relatives entre les flottilles demeurent constantes pendant la période de projection.

De même, si le modèle opérationnel est conditionné à l’aide du modèle d’analyse de la réduction des stocks, les analystes peuvent également préciser (ou estimer) les paramètres de sélectivité pour les différents indices de l’abondance.
Dans ce cas, l’analyse de la réduction des stocks renvoie tous les indices dans DLMtool, en conservant les sélectivités selon l’âge estimées ou définies par l’utilisateur pour chaque indice.
C’est le codage de certaines procédures de gestion qui détermine l’indice qui est utilisé dans les procédures de gestion pendant la période de projection.

Les prises prévues réalisées $C_{y,a}$ sont les recommandations de TAC pour tous les âges (avec une erreur de mise en œuvre possible).
Les prises prévues peuvent tenir compte du taux de rétention ($\dot{R}_{y,a}$) et du taux de mortalité des rejets après leur remise à l’eau $\widetilde{\theta}_{M{\textrm{disc}}}$ en cas de rejets.
L’incertitude liée à la mise en œuvre ($I_\textrm{TAC}$, équation \@ref(eq:dlm-om-itac)) peut également être prise en compte (p. ex. en cas de constante sous-utilisation des TAC) :

$$
C_{y,a} = \frac{B^V_{y,a}} {\sum_{a}^{A}B^V_{y,a}}
\textrm{TAC}_{\mathrm{MP},y}\ I_{\mathrm{TAC},y}\
\frac{\dot{R}_{y,a} + \left( 1 - \dot{R}_{y,a} \right)
{\widetilde{\theta}}_{\textrm{Mdisc}}}{\dot{R}_{y,a}}
(\#eq:dlm-om-cata)
$$

où ($I_\textrm{TAC}$) est définie par l’utilisateur (selon d’autres paramètres; équation \@ref(eq:dlm-om-itac)) et le taux global de rétention selon l’âge $\dot{R}_{y,a}$, est une combinaison d’une rétention propre à l’âge $r_{y,a}$ avec une valeur maximale de $1$ (équation \@ref(eq:dlm-om-ray)) et un taux constant de rejets $\widetilde{\gamma}$ :

$$
\dot{R}_{y,a} = r_{y,a}\ (1 - \widetilde{\gamma}).
(\#eq:dlm-om-retention)
$$

où la rétention propre à l’âge $r_{y,a}$ est modélisée à l’aide de la même forme de courbe double-normale que la sélectivité :

$$
r_{y,a} = \begin{cases}
2^{- \ \frac{{(L_{y,a} - {\widetilde{L}}_{\textrm{rmax}})}^{2}}{\sigma_{\textrm{rasc}}^{2}}} & L_{y,a} \leq {\widetilde{L}}_{\textrm{rmax}}, \\
2^{- \ \frac{{(L_{y,a} - {\widetilde{L}}_{\textrm{rmax}})}^{2}}{\sigma_{\textrm{rdesc}}^{2}}} & L_{y,a} > {\widetilde{L}}_{\textrm{rmax}}, \\
\end{cases}
(\#eq:dlm-om-ray)
$$

où $\widetilde{L}_\textrm{rmax}$ est la longueur à la rétention maximale. Le paramètre d’écart-type du membre ascendant est donné par la longueur à 5 % de rétention $\widetilde{L}_{r5}$ :

$$
\sigma_{\textrm{rasc}} = \frac{{\widetilde{L}}_{r5} - \widetilde{L}_{\textrm{rmax}}}{\sqrt{- \log_2 {0.05}}}
(\#eq:dlm-om-sigrasc)
$$

alors que l’écart-type du membre descendant est donné par la rétention $\widetilde{r}_{L_\infty}$ de la longueur du poisson $\widetilde{L}_\infty$ :

$$
\sigma_{\textrm{rdesc}} = \frac{\widetilde{L}_\infty - \widetilde{{L}}_{\textrm{rmax}}}{\sqrt{- \log_2 {\widetilde{{r}}_{L_\infty}}}}.
(\#eq:dlm-om-sigrdec)
$$

La courbe de rétention s’approche d’une courbe asymptotique à mesure que $\widetilde{r}_{L_\infty} \to 1$.

On calcule ensuite les taux de mortalité par pêche à partir des prises réalisées $C_{y,a}$ avec la contrainte qu’elles ne dépassent pas ${F_\textrm{max}}$ :

$$
F_{y,a} = \min \left( - \ln\left( 1 - \frac{C_{y,a}}{N_{y,a}{w}_{a}} \right),\widetilde{F}_{\max} \right).
(\#eq:dlm-om-Fay)
$$

${F_\textrm{max}}$ peut être ajustée, mais est réglée à 3 par défaut.

## DYNAMIQUE DES OBSERVATIONS

<!-- Parameters for observation dynamics are included in the `Obs` object of DLMtool. -->
La dynamique des observations émule la collecte des données à utiliser dans les procédures de gestion.
Le modèle opérationnel simule deux types fondamentaux de données : 1) les données des séries chronologiques (p. ex. les prises annuelles de 1970 à 2017); et 2) les données sur la composition des prises (p. ex. échantillons de longueur ou d’âge).

### Données des séries chronologiques

Les données des séries chronologiques sont simulées à l’aide de divers types d’erreurs qui seraient possibles dans l’échantillonnage en temps réel des données sur les pêches (p. ex. erreur d’observation log-normale sur les indices de l’abondance).
L’indice standard de l’abondance dans l’outil DLML est calculé en ajoutant l’erreur d’observation et le biais à la biomasse totale annuelle ($B^T_{y}$) au moyen d’un terme $\omega_{I,y}$ qui inclut le biais et l’imprécision des observations de l’indice :

$$
I_{y}^{\textrm{obs}} = \omega_{I,y}\frac{{B^T_{y}}^{\widetilde{\beta}}}{\frac{1}{t_c}\sum_{i = 1}^{t_c}{B^T_{i}}^{\widetilde{\beta}}}
(\#eq:dlm-om-iy)
$$

où $B^T_{y}$ est la biomasse totale donnée par la somme des âges du poids selon l’âge $w_a$, et des nombres selon l’âge $N_{y,a}$ :

$$
B^T_{y} = \sum_{a = 1}^{A}{w_{a}N_{y,a}}
(\#eq:dlm-om-by)
$$

et où $\widetilde{\beta}$ est un paramètre d’hyperstabilité/hyperépuisement.
Quand $\widetilde{\beta}$ est 1, l’indice est lié linéairement à la biomasse féconde $B_y$.
Quand $\widetilde{\beta}$ est supérieur à 1, l’indice est hyperépuisé et se déplace plus rapidement que les véritables changements de la biomasse féconde.
Quand $\widetilde{\beta}$ est inférieur à 1, l’indice est hyperstable et se déplace plus lentement que les véritables changements de la biomasse féconde.
Lorsque l’indice observé est calculé, il est normalisé pour avoir une valeur moyenne de 1 sur toutes les années.

Le terme $\omega_{I,y}$ représente une imprécision dans les observations par $\widetilde{\sigma}_I$ :

$$
\omega_{I,y} = \exp \left( \varepsilon_{I,y} - \frac{{\widetilde{\sigma}}_{I}^2}{2} \right),
(\#eq:dlm-om-omegai)
$$

où le terme de l’erreur log-normale, $\varepsilon$, est tiré d’une distribution normale dont l’écart-type $\sigma_I$ peut être échantillonné au hasard dans chaque simulation :

$$
\varepsilon_{I,y}\sim \textrm{Normal}\left( 0,\widetilde{{\sigma}}_{I} \right).
(\#eq:dlm-om-epsiloni)
$$

Le modèle opérationnel de l’outil DLML peut également être réglé pour refléter un ou plusieurs indices réels observés de la biomasse ou de l’abondance de la période historique, et appliquer à la période projetée la sélectivité du relevé selon l’âge qui a été spécifiée.
Nous recommandons cette approche pour le Cadre des procédures de gestion en supposant que le modèle opérationnel a été conditionné par un modèle d’analyse de la réduction des stocks (annexe \@ref(app:sra)). Dans ce cas, les valeurs de l’indice pour les années $t_1$ à $t_c$ sont définies comme des données et les valeurs de l’indice $I$ (sans erreur d’observation) l’année $y$ (pour $y > t_c$) et pour le relevé $s$ sont calculées comme suit :

$$
I_{y,s} = q_s \sum_{a=1}^A v_{a,s} N_{y,a} w_{y,a}
(\#eq:sra-om-iysn-addind)
$$

pour un indice fondé sur la biomasse et comme suit :

$$
I_{y,s} = q_s \sum_{a=1}^A v_{a,s} N_{y,a}
(\#eq:sra-om-iysb-addind)
$$

pour un indice fondé sur l’abondance.
Le symbole $q_s$ représente la capturabilité estimée par l’analyse de la réduction des stocks (équation \@ref(eq:sra-om-iysb) ou \@ref(eq:sra-om-iysn)).
La sélectivité selon l’âge ($v_{a,s}$) est modélisée à l’aide de la même forme logistique que pour la flottille commerciale (équations \@ref(eq:dlm-om-va)--\@ref(eq:dlm-om-sigldes)), mais avec sa propre forme spécifiée par l’utilisateur ou estimée par l’analyse de la réduction des stocks (équations \@ref(eq:sra-om-vaf)).

Le modèle opérationnel met ensuite une erreur d’observation à l’échelle et l’ajoute à chaque index comme suit :

$$
I_{y,s}^{\textrm{obs}} = \omega_{I,y,s}\frac{{I_{y,s}}^{\widetilde{\beta}}}{\frac{1}{t_c}\sum_{i = 1}^{t_c}{I_{i,s}}}, (\#eq:dlm-om-iy-addind)
$$

avec le terme $\omega_{I,y,s}$ calculé comme suit :


$$
\omega_{I,y,s} = \exp \left( \varepsilon_{I,y,s} - \frac{{{\widetilde{\sigma}}_{I}}^2}{2} \right), (\#eq:dlm-om-omegai-addind)
$$

où le terme de l’erreur log-normale $\varepsilon$, est tiré d’une distribution normale dont l’écart-type $\widetilde{\sigma_I}$ est échantillonné au hasard dans chaque simulation :

$$
\varepsilon_{I,y,s}\sim \textrm{Normal}\left( 0,{{\widetilde{\sigma}}}_{I} \right).
(\#eq:dlm-om-epsiloni-addind)
$$

### Données sur la composition des prises

Deux types d’observations de la composition des prises sont simulés : les prises par classe d’âge par année (CAA) et les prises par classe de longueur par année (CAL). Bien que nous ne proposions pas de procédures de gestion provisoires qui utilisent CAA ou CAL, de futures applications pourraient explorer la valeur de l’information de ces types de données, p. ex. en ce qui concerne la détermination de l’âge à l'aide des otolithes des poissons. Nous décrivons donc la composante modèle d’observation de CAA. Nous ne décrivons pas le modèle d’observation de CAL pour le moment.

Le modèle d’observation de CAA utilise une distribution multinomiale simple pour générer les prises observées selon l’âge pour la période de projection $C_{y,a}^{\textrm{obs}}$, en tenant compte de la taille effective de l’échantillon définie par l’utilisateur ($\widetilde{\textrm{ESS}}_{\textrm{CAA}}$, le nombre d’observations indépendantes) et du nombre annuel moyen d’échantillons ($n_\textrm{CAA}$, nombre d’individus dont l’âge a été déterminé). Par exemple, les échantillons selon l’âge indépendant des prises $\widetilde{\textrm{ESS}}_\textrm{CAA}$ (p. ex. 20 par année) sont échantillonnés dans la proportion $p_a$ par rapport aux prises selon l’âge prédites par le modèle ($C_{y,a}$, équation \@ref(eq:dlm-om-cata)) :

$$
\dot{C}_{y,a}^{\textrm{obs}}\sim \textrm{Multinomial}\left( \widetilde{\textrm{ESS}}_{\textrm{CAA}},p_{a} = \ C_{y,a} \right).
(\#eq:dlm-om-cataobs)
$$

Pour chaque année, on gonfle ensuite la proportion d’échantillons selon l’âge pour la faire correspondre à la taille totale de l’échantillon $\widetilde{n}_\textrm{CAA}$ et on l’arrondit au nombre entier le plus proche ($\textrm{nint}$) :

$$
C_{y,a}^{\textrm{obs}} = \textrm{nint}\left( \ \frac{{\dot{C}}_{y,a}^{\textrm{obs}}\ \widetilde{n}_{\textrm{CAA}}}{\widetilde{\textrm{ESS}}_{\textrm{CAA}}} \right).
(\#eq:dlm-om-cataobs-freq)
$$

En raison de l’arrondissement, ce modèle génère des données sur la fréquence selon l’âge qui sont à peu près égales à la taille moyenne annuelle de l’échantillon :

$$
\sum_{a}^{A}{C_{y,a}^{\textrm{obs}}\ } \approx \widetilde{n}_{\textrm{CAA}}.
(\#eq:dlm-om-cataobs-equality)
$$

## DYNAMIQUE DE LA MISE EN ŒUVRE

<!-- Parameters for implementation dynamics are included in the `Imp` object of DLMtool.-->
<!--The OM includes three types of implementation error-->
<!--, which relate to MPs that provide management advice in terms of Total Allowable Catch (TAC), Total Allowable Effort (TAE) and size limits (SL).-->
Ce Cadre ne tient compte que des procédures de gestion qui produisent des avis de TAC pour les pêches du poisson de fond assujetties à des quotas.
Étant donné que la pêche du poisson de fond en Colombie-Britannique est assujettie à un niveau de présence des observateurs de 100 % en mer et à quai, nous supposons que la sous-déclaration des prises sera négligeable dans les années de projection.
Cependant, pour les espèces non ciblées, il est possible que les TAC ne soient pas pleinement utilisés.
L’incertitude liée à la mise en œuvre des TAC est appliquée dans l’équation \@ref(eq:dlm-om-cata).

Le terme de l’incertitude de la mise en œuvre du TAC ($I_\textrm{TAC}$) est le produit d’une fraction définie par l’utilisateur du TAC capturé $\widetilde{b}_\textrm{TAC}$ et d’un degré de variabilité interannuelle contrôlé par $\widetilde{\sigma}_\textrm{TAC}$.

$$
I_{\textrm{TAC},y} = \widetilde{b}_\textrm{TAC} \cdot \exp \left( \varepsilon_{\textrm{TAC},y} - \frac{{{\widetilde{\sigma}}}_{\textrm{TAC}}^2}{2} \right).
(\#eq:dlm-om-itac)
$$

Par exemple, $b_\textrm{TAC} = 0,7$ équivaut à des déficits de 30 % des prises. Le terme de l’erreur $\varepsilon_{\textrm{TAC},y}$ est tiré d’une distribution normale dont l’écart-type $\widetilde{\sigma}_\textrm{TAC}$ est défini par l’utilisateur et peut être échantillonné au hasard dans chaque simulation :

$$
\varepsilon_{TAC,y}\sim \textrm{Normal}\left( 0,\widetilde{\sigma}_{\textrm{TAC}} \right).
(\#eq:dlm-om-epsilontac)
$$

## CALCUL DES POINTS DE RÉFÉRENCE FONDÉS SUR MSY {#sec:dlmtool-msy-refpts}

Les points de référence biologiques (PRB) du Cadre des procédures de gestion sont actuellement fondés sur les points de référence provisoires suggérés dans le Cadre de l’approche de précaution du Canada [@dfo2006; @dfo2009], où le point de référence limite (PRL) est défini comme la valeur dans le modèle opérationnel de $0,4B_\textrm{MSY}$ et le point de référence supérieur du stock (RSS) est défini comme la valeur dans le modèle opérationnel de $0,8B_\textrm{MSY}$. 
$B_\textrm{MSY}$ est définie comme la biomasse féconde à l’équilibre $B^e$ qui se produirait si le stock était exploité au taux constant de la mortalité par pêche $F^e$ qui produit le rendement maximal durable $\textrm{MSY}$.

Le calcul des PRB est effectué à l’aide des paramètres estimés à l’étape du conditionnement, décrits dans l’annexe \@ref(app:sra).
En l’absence de variabilité annuelle dans les paramètres du cycle biologique ou de la sélectivité, on calcule $F_\textrm{MSY}$ en résolvant numériquement la valeur à l’équilibre $F^e$ qui maximise le rendement à l’équilibre $Y^e$

$$
Y^e = F^e R^e \phi^b,
(\#eq:dlm-om-yeq)
$$

où $R^e$ est le recrutement à l’équilibre (équation \@ref(eq:dlm-om-req)) et $\phi^b$ est la biomasse vulnérable par recrue à l’équilibre, définie dans l’équation \@ref(eq:dlm-om-phib) ci-dessous.

Dans ce Cadre, nous supposons une relation stock-recrue de Beverton-Holt [@beverton1957], bien que DLMtool permette également aux utilisateurs de sélectionner une forme de Ricker [@ricker1954] :

$$
R^e =
\begin{cases}
      \dfrac{\alpha^{\textrm{B}}\phi - 1}{\beta^{\textrm{B}}\phi} & \textrm{Beverton-Holt}\\
      \dfrac{\log(\alpha^{\textrm{R}}\phi)}{\beta^{\textrm{R}}\phi} & \textrm{Ricker},
\end{cases}
(\#eq:dlm-om-req)
$$

où $\alpha^{\textrm{B}}$ et $\beta^{\textrm{B}}$ sont les paramètres de la relation stock-recrue de Beverton-Holt, et $\alpha^{\textrm{R}}$ et $\beta^{\textrm{R}}$ sont les paramètres de la relation stock-recrue de Ricker, définis ci-dessus (voir l’équation \@ref(eq:sra-om-rya).

Selon l’approche de @botsford1981, on calcule la biomasse féconde par recrue à l’équilibre comme suit :

$$
\phi = \sum_{a=1}^A \iota_a w_a m_a,
(\#eq:dlm-om-phi)
$$

où $\iota_a$ est la survie selon l’âge à l’équilibre :

$$
   \iota_a=
      \begin{cases}
            1, & a=1 \\
            \iota_{a-1}e^{-Z^e_{a-1}}, & 1<a<A \\
            \dfrac{\iota_{a-1}e^{-Z^e_{a-1}}}{1-e^{-Z^e_{a}}} , & a=A,
      \end{cases}
(\#eq:dlm-om-survivorship)
$$

et $Z^e_{a}$ est la mortalité totale selon l’âge à l’équilibre :

$$
Z^e_{a} = \widetilde{M} +  F^e_{a}v_{a}.
(\#eq:dlm-om-zeq)
$$

Enfin, en utilisant la même approche, on calcule $\phi^b$ comme suit :

$$
\phi^b = \sum_{a=1}^A \iota_a w_a v_a.
(\#eq:dlm-om-phib)
$$

Après avoir résolu numériquement l’équation \@ref(eq:dlm-om-yeq) pour $F_\textrm{MSY}$, $B_\textrm{MSY}$ est calculée comme suit :

$$
B_{\textrm{MSY}} = \phi\textrm{MSY} R^e,
(\#eq:dlm-om-bmsy)
$$

avec $F^e=F_\textrm{MSY}$ dans l’équation \@ref(eq:dlm-om-survivorship).

Il convient de noter que, comme pour l’équation \@ref(eq:dlm-om-nya), la classe d’âge maximale $A$ est traitée comme un groupe plus dans l’équation \@ref(eq:dlm-om-survivorship). Bien qu’il ne s’agisse pas du paramètre par défaut dans DLMtool, il devient le paramètre par défaut lorsqu’on utilise l’analyse de la réduction des stocks pour conditionner le modèle opérationnel (voir l’explication dans la section \@ref(sec:dlmtool-pop-dynamics)).

## PARAMÈTRES VARIABLES DANS LE TEMPS {#sec:dlmtool-time-varying}

Le modèle opérationnel décrit ci-dessus suppose que les paramètres du modèle représentant la croissance, la sélectivité et la capturabilité de la pêche ne varient pas dans le temps.
DLMtool permet aux utilisateurs de définir un certain nombre de paramètres clés qui varient dans le temps, en fonction des paramètres de pente et de variation qu’ils ont spécifiés.
Par exemple, si les paramètres de croissance $\widetilde{L}_\infty$ et $\widetilde{\kappa}$ sont définis comme variables dans le temps [@carruthers2018, équations 7 et 8 de leur annexe C], alors la courbe de croissance de von Bertalanffy variera dans le temps.
Cela aura une incidence sur d’autres variables du modèle qui dépendent de la longueur, y compris le poids selon l’âge (équation \@ref(eq:dlm-om-wta)), la maturité selon la longueur et l’âge (équations \@ref(eq:dlm-om-matl) et \@ref(eq:dlm-om-mata)) et la sélectivité selon l’âge (équation \@ref(eq:dlm-om-va)).

De même, $M$ peut être définie comme variable dans le temps, soit comme une fonction : 1) d’une augmentation annuelle en pourcentage définie par l’utilisateur ou 2) du poids selon l’âge par rapport au poids maximal, ou les deux [@carruthers2018, équation 4 de l’annexe C].
La capturabilité de la pêche $q$ peut également varier au fil du temps pendant la période de projection, [@carruthers2018, équation 42 de leur annexe D].
Il est à noter que le fait de définir des paramètres de croissance et de mortalité variables dans le temps dans le modèle opérationnel de DLMtool les transférera dans le modèle d’analyse de la réduction des stocks.

En présence de paramètres variables dans le temps, on calcule $B_0$ comme suit :

$$
B_0 = \frac{\sum_{y=1}^{\theta_{a50}}B_\textrm{unfished}^y}{\theta_{a50}},
(\#eq:dlm-om-dyn-bo)
$$

qui est la biomasse féconde moyenne non exploitée les premières années $\theta_{a50}$ (âge à la maturité) de la période historique (arrondie au nombre entier le plus proche) et $B_\textrm{unfished}^y$ est $B_0$ calculée (équation \@ref(eq:dlm-om-bo)).
On peut aussi programmer d’autres interprétations de $B_0$ (p. ex. $B_0$ moyenne sur toute la période historique ou à la fin de la période historique), en fonction de la cible ou du point de référence désiré.

Une croissance, une mortalité naturelle ou une sélectivité variables dans le temps se traduiront par des points de référence fondés sur le rendement maximal durable qui varient dans le temps, car DLMtool calcule $\textrm{MSY}$ et les paramètres connexes (comme $B_\textrm{MSY}$) à chaque pas de temps du modèle, auquel cas les paramètres de rendement annuel seront fondés sur des estimations annuelles des points de référence.
Les analystes doivent faire preuve de prudence avec $B_\textrm{MSY}$ et $B_0$ variables dans le temps.
La diminution des points de référence peut entraîner une amélioration de l’état du stock par rapport aux points de référence inférieurs, ce qui peut causer un effet « d’abaissement » à mesure que le stock et les points de référence diminuent.
Sinon, il est possible de baser les paramètres du rendement sur une $B_\textrm{MSY}$ moyenne tirée de la période historique ou sur un autre point de référence souhaité [p. ex. la biomasse moyenne estimée d’une période historique productive @dfo2009; @forrest2018].

Il est recommandé de résoudre des cibles ou des points de référence appropriés en cas de productivité variable dans le temps en collaboration avec les gestionnaires des pêches, les intervenants et les Premières Nations, car les paramètres de rendement fondés sur des points de référence tels que $B_\textrm{MSY}$ et $B_0$ seront influencés par les méthodes utilisées pour les calculer. Ces décisions devraient être documentées pour assurer la transparence.

Le traitement des points de référence lorsque les paramètres, en particulier les paramètres de productivité comme $\widetilde{M}$ ou $\widetilde{\kappa}$, sont variables dans le temps, est un domaine de recherche actif [p. ex. @haltuch2009; @haltuch2019; @punt2014]. Nous sommes d’avis que le Cadre des procédures de gestion est un environnement approprié pour d’autres approches d’essais par simulation plus poussées pour les points de référence variables dans le temps, et qu’il s’agit d’un important domaine de recherche pour les applications futures du Cadre.

\clearpage

## TIROIRS DE DLMTOOL

```{r tab-om-pars, echo=FALSE, cache=FALSE, message=FALSE, results='asis', eval=TRUE}
 p <- tribble(
~slot_type, ~slot,          ~parameter_symbols,              ~first_sentence,
"Stock",    "maxage",     "$n_a$",                         "L’âge maximal des individus qui est simulé.",
"Stock",    "R0",         "$R_0$",                         "L’ampleur du recrutement non exploité.",
"Stock",    "M",          "$M$",                           "Taux de mortalité naturelle.",
"Stock",    "h",          "$h$",                           "Taux de variation de la relation stock-recrue.",
"Stock",    "Perr",       "$\\sigma_R$",                   "ET de écarts de recrutement dans l’espace logarithmique.",
"Stock",    "AC",         "$\\theta_{\\textrm{AC}}$",      "Autocorrélation dans les écarts de recrutement.",
"Stock",    "Linf",       "$L_{\\infty}$",                 "Longueur maximale prévue de von Bertalanffy.",
"Stock",    "K",          "$\\kappa$",                     "Coefficient de croissance de von Bertalanffy.",
"Stock",    "t0",         "$t_0$",                         "Âge théorique de von Bertalanffy à la longueur zéro.",
"Stock",    "L50",        "$\\theta_{l50}$",               "Longueur à 50\\% de maturité.",
"Stock",    "L50\\_95",    "$\\theta_{l50-95}$",           "Augmentation de longueur de 50 \\% à 95 \\% de maturité.",
"Stock",    "a",          "$\\alpha_W$",                   "Paramètre longueur-poids.",
"Stock",    "b",          "$\\beta_W$",                    "Paramètre longueur-poids.",
   "Flotille",    "L5",         "$L^5$",                         "Longueur la plus courte correspondant à une vulnérabilité de 5\\%.",
"Flotille",    "LFS",        "$L^\\textrm{FS}$",              "Longueur la plus courte pleinement vulnerable à la pêche.",
"Flotille",    "Vmaxlen",    "$V_{L_\\infty}$",               "Vulnérabilité des poissons à la longueur maximale prévue.",
"Flotille",    "LR5",        "${L}_{r5}$",                         "Longueur la plus courte des poissons correspondant à une rétention de 5\\%.",
"Flotille",    "LFR",        "$L_\\textrm{rmax}$",            "Longueur la plus courte des poissons qui sont entièrement conservés.",
 "Flotille",  "Rmaxlen",    "$r_{L_\\infty}$",             "Rétention des poissons à ${L}_\\infty$.",
"Obs.",     "Iobs",       "$\\sigma_I$",                   "ET de l’erreur d’observation de l’indice de l’abondance relative dans l’espace logarithmique.",
"Obs.",     "Cobs",       "$\\sigma_{C}$",                 "ET de l’erreur d’observation des prises dans l’espace logarithmique.",
"Obs.",      "Cbiascv",    "$b_C$",                         "CV contrôlant l’échantillonnage du biais dans les observations des prises.",
"Obs.",     "beta",       "$\\beta$",                      "Paramètre d’hyperstabilité/hyperépuisement.",
"Obs.",     "CAA\\_ESS",  "$\\textrm{ESS}_\\textrm{CAA}$", "Taille effective de l’échantillon du modèle d’erreur d’observation multinomiale des prises selon l’âge.",
"Obs.",     "CAA\\_nsamp", "$n_\\textrm{CAA}$",            "Nombre d’observations des prises selon l’âge par pas de temps.",
"MEO",     "TACFrac",    "$b_\\textrm{TAC}$",             "Fraction moyenne du TAC prélevée.",
"MEO",     "TACSD",      "$\\sigma_\\textrm{bTAC}$",      "ET de la fraction log-normale du TAC prélevée."


)



p %>%
  mutate(slot = paste0("\\texttt{", slot, "}")) %>%
  csasdown::csas_table(format = "latex", col_names = c("Élément du modèle opérationnel", "Tiroir", "Paramètre", "Description"), caption = "Tiroirs, symboles des paramètres et brèves descriptions du modèle opérationnel de DLMtool. Dans la colonne « Éléments du modèle opérationnel », « Obs. » et « MEO » renvoient respectivement aux composantes d’observation et de mise en œuvre. « Tiroirs » est le nom technique des éléments des paramètres dans le progiciel DLMtool R. Tous les paramètres de ce tableau (sauf $n_a$, $\\alpha_W$ et $\\beta_W$) peuvent être définis comme stochastiques avec des tirages à partir d’une distribution pour chaque répétition de la simulation.") %>%
  kableExtra::column_spec(1, width = "1.75cm") %>%
  kableExtra::column_spec(2, width = "1.75cm") %>%
  kableExtra::column_spec(3, width = "1.75cm") %>%
  kableExtra::column_spec(4, width = "9.5cm")
```
