\clearpage

# ANALYSE DE LA RÉDUCTION DES STOCKS POUR CONDITIONNER LES MODÈLES OPÉRATIONNELS {#app:sra}

## RENSEIGNEMENTS GÉNÉRAUX SUR L’ANALYSE DE LA RÉDUCTION DES STOCKS {#sec:sra-background}

Le modèle opérationnel (MO) défini à l’annexe \@ref(app:dlmtool-om) est conditionné en ajustant une analyse de la réduction des stocks (ARS) structurée selon l’âge [@kimura1982; @walters2006] aux données historiques sur les prises observées et les indices de l’abondance (et aux données sur la composition selon l’âge et la longueur, si elles sont disponibles).
Cette étape donne des estimations de paramètres conditionnés pour produire des trajectoires des séries chronologiques conformes aux observations historiques.
Cela est particulièrement important dans les situations où les données sont limitées ou modérées, où l’absence d’évaluation acceptée rend difficile le paramétrage de l’épuisement et de la mortalité par pêche historiques $F$.

Dans la documentation, le terme « analyse de la réduction des stocks » a été utilisé pour décrire un modèle dans lequel les prises totales prévues correspondent aux prises observées.
@kimura1982 ont présenté l’analyse de la réduction des stocks comme une solution de rechange à des modèles d’analyse de production virtuelle (APV) ou de production excédentaire.
L’approche de l’analyse de la réduction des stocks s’applique davantage aux espèces à données limitées que, par exemple, l’analyse de production virtuelle, qui exige des données annuelles sur les prises selon l’âge.
L’analyse de la réduction des stocks utilise une approche de modélisation structurée selon l’âge qui intègre des données sur la mortalité naturelle et le recrutement pour reconstituer l’historique du stock, plutôt que d’adopter une approche regroupée biomasse-dynamique (p. ex. modèle de production excédentaire).
Un autre avantage de l’approche de l’analyse de la réduction des stocks pour les pêches du poisson de fond en Colombie-Britannique est qu’elle permet le conditionnement en fonction de plusieurs indices de l’abondance (p. ex. les indices de différents relevés indépendants de la pêche ou les séries de CPUE des pêches commerciales).

Dans le cas des espèces à données limitées, où il n’est peut-être possible de fournir que des fourchettes de valeurs pour les paramètres clés, l’approche de l’analyse de la réduction des stocks tente de réduire la plage des valeurs de paramètres plausibles afin qu’elle soit cohérente avec les observations historiques, grâce à ses fonctions de vraisemblance.
Autrement dit, elle aide à répondre à la question plus générale suivante : quelles sont les combinaisons de données historiques sur la mortalité par pêche et le recrutement qui auraient pu générer les données observées [@walters2006]?

Nous notons qu’une analyse de la réduction des stocks n’exige pas nécessairement des données sur la composition selon l’âge, dans la mesure où des estimations crédibles de la maturité selon la longueur ou l’âge et de la vulnérabilité selon la longueur ou l’âge peuvent être fournies.
Toutefois, si des données sur la composition selon l’âge ou la longueur sont disponibles, même pour une ou quelques années, on peut les utiliser pour étayer la vulnérabilité selon l’âge dans le modèle.

## ANALYSE DE LA RÉDUCTION DES STOCKS DANS LE CONTEXTE DE DLMTOOL {#sec:sra-dlmtool}

L’analyse de la réduction des stocks décrite ici peut être ajustée à l’aide de TMB [@tmb] avec le progiciel MSEtool dans R via la fonction `SRA_scope()`.
Cette fonction prend un objet du modèle opérationnel de DLMtool (annexe \@ref(app:dlmtool-om)) et les données historiques observées (captures observées, indices de l’abondance et, si elles sont disponibles, données sur la composition), ajuste l’analyse de la réduction des stocks aux données observées, et produit une liste avec un modèle opérationnel mis à jour et des sorties de l’analyse de la réduction des stocks.

Cette approche peut être stochastique (avec échantillonnage Monte Carlo) si le modèle opérationnel est spécifié avec des plages pour les paramètres clés.
Par exemple, le paramètre du taux de variation de la relation stock-recrue ($h$) est habituellement très incertain.
Le modèle opérationnel initial peut préciser une plage de valeurs pour $h$, par exemple : $h \sim \textrm{Uniform} (0,6, 0,9)$.
Dans ce cas, avec $i = 1$ à $n$ (p. ex., $n = 250$) répétitions dans la simulation en boucle fermée, la fonction d’analyse de la réduction des stocks échantillonnera $n$ valeurs du taux de variation à partir de cette distribution et ajustera le modèle d’analyse de la réduction des stocks $n$ fois.
La reconstruction du modèle d’analyse de la réduction des stocks à partir du $i^{\textrm{th}}$ ajustement sera conditionnée à la $i^{\textrm{th}}$ valeur échantillonnée de $h$.
Les valeurs échantillonnées de $h$ (ainsi que tous les autres paramètres d’entrée de l’analyse de la réduction des stocks) sont ensuite enregistrées avec les paramètres estimés pour former le modèle opérationnel conditionné.

## LE MODÈLE D’ANALYSE DE LA RÉDUCTION DES STOCKS {#sec:sra-model}

Le modèle d’analyse de la réduction des stocks peut être conditionné en fonction des prises ou de l’effort de pêche.
Pour les espèces de poisson de fond de la Colombie-Britannique, nous recommandons de conditionner le modèle en fonction des prises.
Depuis l’introduction du niveau de présence à 100 % des observateurs en mer et à quai en 1996, les données sur les prises sont connues avec très peu d’erreurs.
Les données sur l’effort dans les pêches plurispécifiques sont plus difficiles à interpréter.
Si le modèle est conditionné en fonction des prises, l’analyse de la réduction des stocks produira des prises prévues qui correspondront aux prises observées.
Une série chronologique complète de la variable de conditionnement (c.-à-d. les prises) est requise.

Si la série chronologique sur les prises est suffisamment longue, on peut supposer que la période historique commence à un état non exploité ($B_{t=1} = B_0$, où $B_{t=1}$ est la biomasse féconde la première année historique et $B_0$ représente la taille du stock à l’équilibre à l’état non exploité).
Toutefois, pour certaines espèces de poisson de fond de la Colombie-Britannique, il se peut que les registres des prises soient moins fiables avant l’introduction du système complet de surveillance des prises (p. ex. en 1996 pour la flottille de chalutiers de poisson de fond).
Dans ces cas, le modèle d’analyse de la réduction des stocks est configuré de manière à supposer une valeur pour les prises à l’équilibre dans chaque flottille $f$ avant la première année de la série chronologique sur les prises ($C^{\textrm{eq}}_f$).
Nous précisons qu’il n’est pas nécessaire que $C^{\textrm{eq}}_f$ soit les véritables prises avant la première année---des facteurs comme le recrutement, la mortalité causée par les prédateurs ou toute autre tendance du nombre de prises auraient pu causer l’épuisement initial estimé---mais que $C^{\textrm{eq}}_f$ représente les prises correspondantes à l’équilibre.
L’analyse de la réduction des stocks utilisera ensuite cette valeur pour estimer l’épuisement initial ($\frac{B_{t=1}}{B_0}$) la première année de la période historique.
$C^{\textrm{eq}}_f$ est donc un moyen pratique d’initialiser le modèle à différents niveaux d’épuisement.

L’épuisement initial est difficile à estimer avec précision sans d’autres sources d’information (p. ex. un long indice de l’abondance ou des données sur la composition selon l’âge).
C’est pourquoi nous recommandons de traiter $C^{\textrm{eq}}_f$ comme un axe majeur d’incertitude si cette approche est adoptée.
Une autre approche consiste à utiliser des méthodes de reconstitution des prises [p. ex. @porch2004; @starr2017] pour reconstituer la série chronologique sur les prises à l’époque où le stock était considéré comme non exploité.
Bien que cette approche évite l’incertitude associée à l’estimation de l’épuisement en fonction de $C^{\textrm{eq}}_f$, elle peut introduire d’autres sources d’incertitude associées à l’approche de reconstitution.

Outre la série chronologique sur le conditionnement, on peut utiliser d’autres types de données, qui n’ont pas besoin d’être disponibles chaque année de la série chronologique :

- Séries chronologiques des indices de l’abondance (sous forme de biomasse du relevé ou de CPUE dépendantes de la pêche);
- Données sur la composition selon l’âge;
- Données sur la composition selon la longueur;
- Longueur moyenne (données des pêches commerciales ou des relevés).

L’analyse de la réduction des stocks peut intégrer plusieurs relevés et flottilles.
Il est généralement nécessaire d’inclure un de ces types de données en plus de la série chronologique sur les prises utilisée pour le conditionnement afin d’étayer les estimations de l’épuisement.
Même dans les cas où les données disponibles sont sporadiques, elles peuvent être utiles pour estimer l’épuisement.
Par exemple, un échantillon de composition selon l’âge d’une seule année récente qui révèle une structure selon l’âge très tronquée peut dénoter un stock fortement épuisé.
Les données sur la composition selon l’âge d’une année ou de quelques années peuvent également renseigner sur la sélectivité, qui à son tour éclaire les estimations de la taille du stock.

### Paramètres du modèle d’analyse de la réduction des stocks

Les paramètres spécifiés à l’avance du modèle opérationnel qui sont requis pour définir la portée de l’analyse de la réduction des stocks sont les suivants (les noms des tiroirs de DLMtool sont fournis dans le tableau \@ref(tab:tab-om-pars)) :

- Paramètres de la croissance $L_{\infty}$, $\kappa$ et $a_{0}$;

- Facteurs de conversion longueur-poids $\alpha_{W}$ et $\beta_{W}$;

- Paramètres de la maturité $\theta_{l50}$ et $\theta_{l50-95}$;

- Mortalité naturelle $M$;

- Taux de variation $h$.

Si la croissance, la maturité ou la mortalité naturelle sont définies comme étant variables dans le temps durant la période historique, l’analyse de la réduction des stocks mettra également en œuvre un cycle biologique variable dans le temps dans le modèle d’estimation.

- Type de relation stock-recrue (Beverton-Holt ou Ricker);

- Recrutement non exploité ($R_0$), qui est utilisé comme valeur de départ pour l’estimation si le modèle est conditionné en fonction des prises;

- Paramètres de la sélectivité $L_{5}$, $L_{LFS}$ et $V_{L_\infty}$.

S’il n’y a pas de données sur l’âge ou la composition selon la longueur, la sélectivité dans le modèle est fixée à ces valeurs.
Sinon, le membre ascendant de la sélectivité est estimé à l’aide des données sur la composition selon l’âge ou la longueur.
Si l’on suppose que la sélectivité est en forme de dôme, alors le membre descendant peut être fixé ou estimé dans l’analyse de la réduction des stocks. Voir l’équation \@ref(eq:sra-om-vaf).

- L’autocorrélation de premier ordre de l’écart de recrutement ($\theta_{\textrm{AC}}$) est estimée après coup à partir des estimations de l’écart de recrutement.

- L’écart-type des écarts de recrutement $\sigma_{R}$ est intégré comme donnée d’entrée. Les écarts de recrutement historiques sont mis à jour par le modèle d’analyse de la réduction des stocks (équation \@ref(eq:sra-om-rya)), tandis que les écarts de recrutement dans la période de projection sont échantillonnés avec autocorrélation (équation \@ref(eq:dlm-om-recdev)).

Si l’épuisement initial (équation \@ref(eq:sra-om-d1)) est estimé, on ajuste alors les écarts annuels de recrutement pour la première année afin de produire l’abondance estimée selon l’âge pour la première année du modèle d’analyse de la réduction des stocks (équation \@ref(eq:sra-om-rya)).

Si plusieurs flottilles sont utilisées pour le conditionnement, on mettra à jour la sélectivité selon l’âge ($v_{a,f}$, équation \@ref(eq:sra-om-vaf)) en fonction de la mortalité relative par pêche dans les flottilles.
L’hypothèse par défaut dans la période de projection de la simulation en boucle fermée est que la sélectivité et la mortalité relative par pêche dans les flottilles sont identiques à celles de la dernière année historique $t_c$.
Voir la section \@ref(sec:dlmtool-fleet-dynamics).

## DESCRIPTION DU MODÈLE D’ANALYSE DE LA RÉDUCTION DES STOCKS

### Vulnérabilité selon l’âge et mortalité

La sélectivité selon l’âge (ou vulnérabilité selon l’âge) propre à la flottille ($v_{a,f}$) est fondée sur la longueur et modélisée de la même manière que dans le modèle opérationnel de DLMtool (annexe \@ref(app:dlmtool-om)), la seule différence étant que plusieurs flottilles ($f$) peuvent être prises en compte.
Pour la flottille $f$ avec une sélectivité asymptotique, on utilise une fonction logistique à deux paramètres, avec des paramètres qui définissent la longueur à 5 % de sélectivité ($L^5_f$) et la longueur à pleine sélectivité $L^{\textrm{FS}}_f$.
Pour la sélectivité en forme de dôme, on utilise aussi un troisième paramètre, la sélectivité à $L_{\infty}$, $v^{L_{\infty}}_f$.
La sélectivité fondée sur la longueur est convertie en sélectivité fondée sur l’âge comme suit :

$$
v_{a,f} =
\begin{cases}
2^{-[(L_{a} - L^{\textrm{FS}}_f)/(\sigma^{\textrm{asc}}_f)]^2} & \textrm{si } L_{a} < L^{\textrm{FS}}_f\\
1 & \textrm{si logistique et } L_{a} \ge L^{\textrm{FS}}_f\\
2^{-[(L_{a} - L^{\textrm{FS}}_f)/(\sigma^{\textrm{des}}_f)]^2} & \textrm{si en forme de dôme et } L_{a} \ge L^{\textrm{FS}}_f,
\end{cases}
(\#eq:sra-om-vaf)
$$

où $L_{y,a}$ est la longueur moyenne selon l’âge, et $\sigma^{\textrm{asc}}_f = (L^5_f - L^{\textrm{FS}}_f)/\sqrt{-\log_2(0.05)}$ et $\sigma^{\textrm{des}}_f = (L_{\infty} - L^{\textrm{FS}}_f)/\sqrt{-\log_2(v^{L_{\infty}})}$ contrôlent la forme des membres ascendant et descendant, respectivement, de la fonction de sélectivité. Dans ce paramétrage, la sélectivité fondée sur la longueur est constante dans le temps. La sélectivité correspondante fondée sur l’âge est constante dans le temps si la croissance ne varie pas dans le temps.

Voir la description du traitement de plusieurs flottilles dans le modèle opérationnel de DLMtool pendant la période de projection à l’annexe \@ref(app:dlmtool-om), section \@ref(sec:dlmtool-fleet-dynamics.

La mortalité totale $Z$ de l’année $y$ et pour l’âge $a$ est donnée par la formule

$$
Z_{y,a} = M + \Sigma_f v_{a,f} F_{y,f},
(\#eq:sra-om-zya)
$$

où $F_{y,f}$ est la mortalité par pêche l’année $y$ dans la flottille $f$, et $M$ est la mortalité naturelle, supposée constante ici.

### Répartition de la population initiale

On suppose que les nombres selon l’âge la première année du modèle $y=1$ sont en état d’équilibre :

$$
N_{1,a} =
\begin{cases}
      R^{\textrm{eq}} & a = 1 \\
      N_{1,a-1} \exp(-Z^{\textrm{eq}}_a) & a = 2, \ldots, A-1\\
      \dfrac{N_{1,a-1} \exp(-Z^{\textrm{eq}}_a)}{1 - \exp(-Z^{\textrm{eq}}_A)} & a = A,
\end{cases}
(\#eq:sra-om-numinit)
$$

où $R^{\textrm{eq}}$ est le recrutement à l’équilibre (équation \@ref(eq:sra-om-recinit)) et $Z^{\textrm{eq}}_a$ est le taux de mortalité totale à l’équilibre :

$$
Z^{\textrm{eq}}_a = M + \Sigma_f v_{a,f} F^{\textrm{eq}}_f.
(\#eq:sra-om-zeq)
$$

Si l’on suppose que le stock n’est pas exploité la première année de la période historique ($y= t_1$), on modélise les conditions sans exploitation en fixant $F^{\textrm{eq}}_f = 0$. Dans la pratique, c’est l’utilisateur qui règle à zéro les prises à l’équilibre pour chaque flottille ($C^\textrm{eq}_f = 0$).

Si le stock n’était pas non exploité l’année $t_1$, on suppose que la population est dans un état d’équilibre avec des prises égales à des prises à l’équilibre définies par l’utilisateur ($C^\textrm{eq}_f$), définies comme une fraction des prises observées l’année $t_1$. Dans ce cas, l’analyse de la réduction des stocks estime les prises prévues à l’équilibre ($C^{\textrm{eq,pred}}_f$), qui sont ajustées à $C^\textrm{eq}_f$, avec un écart-type très faible (0,01) dans la fonction de vraisemblance (équation \@ref(eq:sra-om-like-eqcatch)). Les prises à l’équilibre sont prédites à l’aide de l’équation de Baranov, additionnées entre les flottilles ($f=1:nf$) et les âges ($a=1:A$) :

$$
C^{\textrm{eq,pred}}_f = \sum_{a=1}^A\dfrac{v_{a,f}F^{\textrm{eq}}_f}{Z^{\textrm{eq}}_a}(1-\exp^{-Z^{\textrm{eq}}})N_{1,a}w_a,
(\#eq:sra-om-ceqpred)
$$

où $F^{\textrm{eq}}_f$ sont les paramètres estimés.

Après avoir obtenu $Z^{\textrm{eq}}_a$, on calcule le recrutement à l’équilibre à l’aide d’une relation stock-recrue de Beverton-Holt [@beverton1957] ou de Ricker [@ricker1954] :

$$
R^{\textrm{eq}} =
\begin{cases}
      \dfrac{\alpha^{\textrm{B}}\phi - 1}{\beta^{\textrm{B}}\phi} & \textrm{Beverton-Holt}\\
      \dfrac{\log(\alpha^{\textrm{R}}\phi)}{\beta^{\textrm{R}}\phi} & \textrm{Ricker},
\end{cases}
(\#eq:sra-om-recinit)
$$

où $\phi$ correspond aux reproducteurs par recrue à l’équilibre (voir l’équation \@ref(eq:dlm-om-phi)), $\alpha^{\textrm{B}}$ et $\beta^{\textrm{B}}$ sont les paramètres de la relation stock-recrue de Beverton-Holt, et $\alpha^{\textrm{R}}$ et $\beta^{\textrm{R}}$ sont les paramètres de la relation stock-recrue de Ricker, dérivés du taux de variation des paramètres définis par l’utilisateur ($h$) et $R_0$, où 
$\alpha^{\textrm{B}} = \frac{4h}{(1-h)\phi_0}$,
$\beta^{\textrm{B}} = \frac{5h-1}{(1-h)B_0}$
et 
$\alpha^{\textrm{R}} = \frac{(5h)^{1.25}}{\phi_0}$, $\beta^{\textrm{R}} = \frac{\log(5h)}{B_0}$, et où $\phi_0$ et $B_0$ sont les reproducteurs par recrue non exploités et la biomasse féconde non exploitée, respectivement, et $B_0$ est dérivée de $R_0\phi_0$.

L’épuisement initial du stock reproducteur est alors donné par la formule suivante :

$$
\frac{B_{1}}{B_0},
(\#eq:sra-om-d1)
$$

où

$$
B_{1} = \sum_a^A w_{a} m_{a} N_{1,a}.
(\#eq:sra-om-b1)
$$

Il devrait être évident à partir des équations \@ref(eq:sra-om-ceqpred), \@ref(eq:sra-om-recinit) et \@ref(eq:dlm-om-phi) que, dans les cas où les données sont limitées, les paramètres $R_0$ et $F^{\textrm{eq}}_f$ sont très confusionnels car ils informent tous deux la taille de la population par $R^{\textrm{eq}}$. Dans de tels cas, il est fortement recommandé de traiter $C^\textrm{eq}$ comme un axe majeur d’incertitude, car il déterminera fortement l’épuisement initial et la taille du stock. Nous notons également que les paramètres ($q_s$) de mise à l’échelle des observations des relevés par rapport à la biomasse vulnérable (équation \@ref(eq:sra-om-iysb)) seront également confusionnels avec $R_0$ et $F^{\textrm{eq}}_f$.


### Équations des dynamiques

Après avoir établi la distribution selon l’âge de la population à l’équilibre pour la première année du modèle, l’abondance de la population $N_{y,a}$ pour les années suivantes est donnée par la formule

$$
N_{y,a} =
\begin{cases}
      R_y & a = 1\\
      N_{y-1,a-1}\ e^{-Z_{y-1,a-1}} & a = 2, \ldots, A - 1,\\
      N_{y-1,a-1}\ e^{-Z_{y-1,a-1}} + N_{y-1,a}\ e^{-Z_{y-1,a}} & a = A,
\end{cases}
(\#eq:sra-om-nya)
$$

où $R_y$ est le recrutement annuel (équation \@ref(eq:sra-om-rya)) et $A$ est l’âge maximal, traité comme un groupe plus.

Le recrutement annuel $R_y$ est modélisé comme suit :

$$
R_y =
\begin{cases}
      \dfrac{\alpha^{\textrm{B}} B_{y-1}}{1 + \beta^{\textrm{B}}B_{y-1}} \exp(\varepsilon_y - 0.5 \tau^2) & \textrm{Beverton-Holt}\\
      \alpha^{\textrm{R}} B_{y-1} \exp(-\beta^{\textrm{R}} B_{y-1})\exp(\varepsilon_y - 0.5 \tau^2) & \textrm{Ricker},
\end{cases}
(\#eq:sra-om-rya)
$$

où $\varepsilon_y$ correspond aux écarts de recrutement (ici dans l’espace logarithmique par rapport à l’espace naturel dans l’annexe \@ref(app:dlmtool-om)) et $\tau$ est l’écart-type des écarts aléatoires et $B_y$ est la biomasse féconde annuelle, donnée par :

$$
B_y = \sum_a^A w_{a} m_{a} N_{y,a},
(\#eq:sra-om-by)
$$

où $m_{y,a}$ et $w_{y,a}$ sont respectivement la maturité selon l’âge et le poids selon l’âge (équations \@ref(eq:dlm-om-vonb) et \@ref(eq:dlm-om-wta)).

### Prises selon l’âge

Si le modèle est ajusté aux données sur la composition selon l’âge, les prises (en nombres) $C^N$ selon l’âge pour la flottille $f$ sont

$$
C^N_{y,a,f} = \dfrac{v_{a,f} F_{y,f}}{Z_{y,a}} N_{y,a} (1 - \exp(-Z_{y,a}).
(\#eq:sra-om-cyaf)
$$

On peut estimer $F_{y,f}$ comme des paramètres (ou la résoudre itérativement pour la faire correspondre aux prises observées).

### Prises selon la longueur

Si le modèle est ajusté aux données sur la composition selon la longueur, on calcule les prises selon la longueur en supposant une longueur selon l’âge à distribution normale $P(\ell,a)$, où

$$
C^N_{y,\ell,f} = \sum_a C^N_{y,a,f} P(\ell \vert a),
(\#eq:sra-om-cylf)
$$

et

$$
P(\ell \vert a) =
\begin{cases}
      \phi^L(L'_{\ell+1}) & \ell = 1\\
      \phi^L(L'_{\ell+1}) - \phi(L'_\ell) & \ell = 2, \ldots, L - 1,\\
      1 -\phi^L(L'_\ell) & \ell = L,
\end{cases}
(\#eq:sra-om-pla)
$$

où $L'_{\ell}$ est la longueur à la limite inférieure de la catégorie de longueur $\ell$ et $\phi^L(L'_{\ell})$ est la fonction de distribution cumulative d’une variable normale dont la moyenne est $\tilde{L}_{y,a}$ (la longueur moyenne prévue à l’âge $a$) et l’écart-type est $\tilde{L}_{y,a} \times CV^L$, $CV^L$ étant le coefficient de variation de la longueur moyenne selon l’âge.

Les prises ajustées en poids $C_{y,f}$ sont

$$
C_{y,f} = \sum_a C^N_{y,a,f} w_{y,a}.
(\#eq:sra-om-cyfw)
$$

La longueur moyenne des prises $\bar{L}_{y,f}$ est

$$
\bar{L}_{y,f} = \dfrac{\sum_{\ell} L_{\ell} C^N_{y,\ell,f}}{\sum_{\ell} C^N_{y,\ell,f}},
(\#eq:sra-om-lmean)
$$

où $L_\ell$ est le milieu de la catégorie de longueur $\ell$.

La proportion des prises selon l’âge est

$$
p_{y,a,f} = \dfrac{C^N_{y,a,f}}{\sum_a C^N_{y,a,f}}.
(\#eq:sra-om-pyaf)
$$

La proportion de prises selon la longueur est

$$
p_{y,\ell,f} = \dfrac{C^N_{y,\ell,f}}{\sum_{\ell}C^N_{y,\ell,f}}.
(\#eq:sra-om-pylf)
$$

## Relevé

Si le $s^{\textrm{th}}$ relevé est fondé sur la biomasse, la valeur $I_{y,s}$ du relevé est calculée comme suit :

$$
I_{y,s} = q_s \sum_a v_{a,s} N_{y,a} w_{y,a},
(\#eq:sra-om-iysb)
$$

où $q$ est le coefficient d’échelle et $s$ indexe chaque relevé.

Si le relevé est fondé sur l’abondance, alors

$$
I_{y,s} = q_s \sum_a v_{a,s} N_{y,a}.
(\#eq:sra-om-iysn)
$$

## Vraisemblances

Si le modèle est conditionné en fonction des prises et que les taux de mortalité par pêche sont des paramètres estimés, alors la composante de log-vraisemblance $\Lambda_1$ des prises est

$$
\Lambda_1 = \sum_f \left[\lambda^{C}_f \sum_y \left(-\log(0.01) - \dfrac{[\log({C}^{\textrm{obs}}_{y,f}) - \log({C}^{\textrm{pred}}_{y,f})]^2}{2 \times 0,01^2}\right)\right],
(\#eq:sra-om-like-catch)
$$

où $\textrm{obs}$ et $\textrm{pred}$ indiquent les quantités observées et prévues, respectivement, et $\lambda$ sont les poids de la vraisemblance. Avec un très petit écart-type pour la vraisemblance des prises (0,01) par rapport à la variance dans d’autres composantes de la vraisemblance, les prises prévues devraient correspondre presque parfaitement aux prises observées.

La composante de log-vraisemblance $\Lambda_2$ des données de relevé est

$$
\Lambda_2 = \sum_s \left[ \lambda^I_s \sum_y \left(-\log(\sigma_{y,s}) - \dfrac{[\log(I^{\textrm{obs}}_{y,s}) - \log(I^{\textrm{pred}}_{y,s})]^2}{2\sigma_{y,s}^2}\right) \right].
(\#eq:sra-om-like-ind)
$$

La composante de log-vraisemblance $\Lambda_3$ des données sur les prises selon l’âge est

$$
\Lambda_3 = \sum_f \lambda^A_f \left[\sum_y O^A_{y,f} \sum_a p^{\textrm{obs}}_{y,a,f} \log(p^{\textrm{pred}}_{y,a,f})\right],
(\#eq:sra-om-like-caa)
$$

où $O^A$ est la taille des échantillons annuels pour les compositions selon l’âge.

La composante de log-vraisemblance $\Lambda_4$ des données sur les prises selon la longueur est

$$
\Lambda_4 = \sum_f \lambda^L_f \left[ \sum_y O^L_{y,f} \sum_{\ell} p^{\textrm{obs}}_{y,\ell,f} \log(p^{\textrm{pred}}_{y,\ell,f})\right],
(\#eq:sra-om-like-cal)
$$

où $O^L$ est la taille des échantillons annuels pour les compositions selon la longueur.

La composante de log-vraisemblance $\Lambda_5$ des longueurs moyennes observées dans les prises est

$$
\Lambda_5 = \sum_f \lambda^{\bar{L}}_f\left[ \sum_y \left(-\log(\omega_f) - \dfrac{[\bar{L}^{\textrm{obs}}_{y,f} - \bar{L}^{\textrm{pred}}_{y,f}]^2}{2 \omega^2_f}\right)\right],
(\#eq:sra-om-like-meanl)
$$

où $\omega_f$ est l’écart-type des longueurs moyennes.

La composante de log-vraisemblance $\Lambda_6$ des écarts aléatoires annuels estimés du recrutement $\varepsilon_y$ dans l’espace logarithmique est

$$
\Lambda_6 = \Sigma_y\left(-\log(\tau) - \dfrac{\varepsilon_y^2}{2 \tau^2}\right),
(\#eq:sra-om-like-recdevs)
$$

où $\tau$ est l’écart-type des écarts aléatoires du recrutement.

La composante de log-vraisemblance $\Lambda_7$ des prises à l’équilibre est

$$
\Lambda_7 = \sum_f \lambda^{C}_f \left(-\log(0.01) - \dfrac{[\log(C^{\textrm{eq,obs}}_f) - \log(C^{\textrm{eq,pred}}_f)]^2}{2 \times 0,01^2}\right).
(\#eq:sra-om-like-eqcatch)
$$

La log-vraisemblance totale $\textrm{LL}$ à maximiser est

$$
\textrm{LL} = \sum_{i=1}^7\Lambda_i.
(\#eq:sra-om-like-tot)
$$

