---
title: "Un Cadre des procédures de gestion pour le poisson de fond en Colombie-Britannique"
author: |
  Sean C. Anderson^1^,
  Robyn E. Forrest^1^,
  Quang C. Huynh^2^,
  Elise A. Keppel^1^
author_list: "Anderson, S.C., Forrest, R.E., Huynh, Q.C., Keppel, E.A."
address: |
  ^1^Station biologique du Pacifique\
     Pêches et Océans Canada, 3190, chemin Hammond Bay\
     Nanaimo (Colombie-Britannique) V9T 6N7, Canada\
  ^2^Institut des océans et des pêches\
     LRAE de l’Université de la Colombie-Britannique, 2202, Main Mall\
     Victoria (Colombie-Britannique) V6T 1Z4, Canada\
year: 2021
report_number: nnn
region: Région du Pacifique
abstract: |
  Le Plan de gestion intégrée des pêches du poisson de fond de la région du Pacifique énumère environ 80 stocks de poissons pour lesquels il faut fixer des totaux autorisés des captures annuels, dont la plupart sont appliqués sous forme de quotas individuels transférables dans la pêche intégrée du poisson de fond de la Colombie-Britannique (C.-B.). Pour la majorité des stocks rencontrés dans la pêche intégrée du poisson de fond, les données sont considérées comme limitées; les stocks définis comme étant à données limitées sont ceux pour lesquels les données sont insuffisantes pour que l’on puisse en estimer de façon fiable l’état, l’abondance ou la productivité au moyen de méthodes classiques d’évaluation des stocks comme les modèles statistiques des prises selon l’âge. Dans les dernières décennies, les évaluations des stocks de poisson de fond menées par Pêches et Océans Canada (MPO) se sont concentrées sur les stocks riches en données, ce qui a donné un sous-ensemble de stocks pour lesquels on dispose d’évaluations complètes, tandis que de nombreux stocks sur lesquels on a moins de données informatives ne sont toujours pas évalués.

  En vertu du Cadre pour la pêche durable du MPO, légiféré par les dispositions sur les stocks de poissons de la *Loi sur les pêches*, les stocks de poissons doivent être gérés à des niveaux durables, plus précisément à des niveaux de biomasse supérieurs au point de référence limite (PRL). Dans le cas des stocks à données limitées, les données sont souvent insuffisantes pour que l’on puisse tenir compte adéquatement de l’incertitude dans l’évaluation de l’état des stocks par rapport aux points de référence biologiques dans les évaluations classiques. Au lieu de nous concentrer sur la connaissance explicite de l’état actuel des stocks, nous proposons une approche axée sur la gestion qui met l’accent sur le choix de procédures de gestion (PG) offrant une probabilité élevée de maintenir les stocks de poissons au-dessus des points de référence implicitement connus dans différents états de la nature possibles, quelles que soient la qualité et la quantité des données disponibles.

  À l’échelle mondiale, on se tourne vers des approches de procédures de gestion (ou d’évaluation des stratégies de gestion) pour fournir des avis scientifiques sur les stocks de poissons par simulation en boucle fermée. La simulation en boucle fermée diffère de l’évaluation classique des stocks parce qu’elle simule la rétroaction entre la mise en œuvre des procédures de gestion et un système simulé représentant le stock de poisson et son environnement, décrite par un ou plusieurs modèles opérationnels (MO). Le présent document décrit une méthodologie pour élaborer des modèles opérationnels appropriés, mettre à l’essai des séries de procédures de gestion et déterminer celles qui répondent le mieux aux objectifs de la gestion des pêches et des intervenants. Nous présentons six étapes de pratiques exemplaires pour les approches de procédures de gestion : 1) la définition du contexte décisionnel, 2) l’établissement des objectifs et des paramètres de rendement, 3) la spécification des modèles opérationnels, 4) la sélection des procédures de gestion possibles, 5) la réalisation des simulations en boucle fermée et 6) la présentation des résultats pour évaluer les compromis. Nous décrivons ensuite l’approche que nous proposons (le « Cadre des procédures de gestion ») et comment elle cherche à réaliser chacune de ces étapes de pratiques exemplaires. Le Cadre comprend des objectifs de pêche et de conservation provisoires et des paramètres de rendement fondés sur les politiques du Cadre pour la pêche durable, une bibliothèque provisoire de procédures de gestion à données limitées qui sont appropriées pour les stocks de poisson de fond de la Colombie-Britannique et des visualisations provisoires pour aider les décideurs à évaluer le rendement des procédures et les compromis entre elles.

  Nous effectuons une étude de cas du stock de plie royale (*Glyptocephalus zachirus*) dans la zone de gestion du poisson de fond de la côte ouest de l’île de Vancouver (zone 3CD) pour faire la démonstration d’une application du Cadre des procédures de gestion. Cette étude de cas utilise six modèles opérationnels de l’ensemble de référence et deux modèles opérationnels de l’ensemble de robustesse. Elle présente un ensemble de procédures de gestion fondées sur des indices de relevé, de prises constantes et de procédures de gestion fondées sur la production excédentaire qui offrent une probabilité supérieure à 0,9 (neuf fois sur dix) de maintenir la biomasse au-dessus du PRL à long terme (35 à 50 ans dans le futur) tout en conservant une probabilité supérieure à 0,8 (quatre fois sur cinq) de maintenir les prises au moins aux niveaux moyens récents (5 ans) dans le futur proche (1 à 10 ans) dans les modèles opérationnels de l’ensemble de référence. Nous présentons également des paramètres de rendement liés à la probabilité à long terme que la biomasse demeure au-dessus du point de référence supérieur du stock, la probabilité à long terme de pêcher en deçà de *F*~MSY~ (mortalité par pêche au rendement maximal durable), la probabilité à long terme de maintenir les prises au-dessus des niveaux moyens récents et la probabilité que la variabilité des prises demeure sous les niveaux historiques. Pour quatre des procédures de gestion, les paramètres de rendement n’étaient que légèrement inférieurs dans les modèles opérationnels de l’ensemble de robustesse, comparativement à ceux de l’ensemble de référence, tandis que les autres procédures de gestion étaient plus sensibles à ces scénarios de robustesse des modèles opérationnels.

  Nous mettons en lumière les problèmes liés aux points de référence, à l’ajustement des procédures de gestion, à la fréquence et aux déclencheurs des évaluations, à l’inclusion des effets environnementaux, à l’évaluation de la valeur de l’information et à l’utilisation de ce Cadre dans les plans de rétablissement des stocks. Dans l’ensemble, notre Cadre met l’accent sur la transparence et la reproductibilité et, à cette fin, nous élaborons un progiciel connexe pour le logiciel statistique R qui facilite les applications du Cadre. Globalement, notre intention est d’améliorer la capacité de la Direction des sciences de la région du Pacifique à fournir des avis sur les prises fondés sur des données probantes pour un plus grand nombre de stocks de poisson de fond — quelles que soient les limites des données — d’une manière normalisée et transparente, conformément au Cadre pour la pêche durable du MPO, aux dispositions sur les stocks de poissons de la *Loi sur les pêches* et aux pratiques exemplaires internationales.

header: "" # or "" to omit
output:
 csasdown::resdoc_pdf:
   french: true
# ------------
# End of options to set
knit: bookdown::render_book
link-citations: true
bibliography: refs.bib
csl: csl/csas.csl # or csl/csas-french.csl for French
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
# adjust as desired:
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = if (knitr:::is_latex_output()) "knitr-figs-pdf/" else "knitr-figs-docx/",
  cache.path = if (knitr:::is_latex_output()) "knitr-cache-tex/" else "knitr-cache-docx/",
  fig.asp = 0.618,
  fig.width = 7.5,
  out.width = "5in",
  echo = FALSE,
  autodep = TRUE,
  cache = TRUE,
  cache.comments = FALSE,
  dev = if (knitr:::is_latex_output()) "png" else "png",
  dpi = 180,
  fig.align = "center",
  fig.pos = "htb"
)
options(kableExtra.latex.load_packages = FALSE)
```

```{r load-libraries, cache=FALSE}
# rstanarm loading MUST COME BEFORE THE OutDec OPTION!!!!!!!!!!!!
# much time wasted on 2021-04-07
library(rstanarm)
french <- TRUE

if (french){
  csl <- "csl/csas.csl"
  options(OutDec =  ",")
  options(french = TRUE)
} else {
  options(french = FALSE)
  csl <- "csl/csas.csl"
}

# add other packages here:
library(gfplot)
library(gfutilities)
library(gfdlm)
library(csasdown)
library(DLMtool)
library(MSEtool)
library(rfishbase)
library(RColorBrewer)
library(tidyverse)
library(here)
library(rosettafish)
filter <- dplyr::filter
options(tinytex.verbose = TRUE)
knitr::opts_chunk$set(crop = NULL)
```
